- src/libpython.h
- vignettes/arrays.Rmd
The vignette follows from legitimate confusion brought up in https://github.com/rstudio/reticulate/issues/9
The new C function gets at PyArray_FLAGS and may be useful in future performance enhancements.
> Vignette discussing array indexing, and a trivial new  C function

- src/python.cpp
- tests/testthat/test-python-numpy.R
I had previously erred on the side of preserving integer vs. float representation but I think this might lead to overflow in some cases. This change maps all of the NumPy integer types that *could* be > 32 bits into REALSXP rather than INTSXP within R.
@bwlewis Let me know if you think this makes sense.
> Map numpy long integer types to REALSXP

- DESCRIPTION
- src/interrupt.cpp
- src/interrupt.h
- src/python.cpp
- src/tinythread.h
This code implements the ability to interrupt executing Python code using the standard R interrupt handling mechanism.
Since execution of Python code occurs within native C++ code the normal R interpreter checking for interrupts that occurs during do_eval does not have  a chance to execute. Typically within Rcpp packages long running user code will call `Rcpp::checkForInterrupts` periodically to check for an interrupt and exit via an exception if there is one. However there is no opportunity  to do this during Python execution, so we need to find a way to get periodic callbacks during the Python interpreter's processing to perform this check.
This is provided for via the `Py_AddPendingCall` function, which enables the scheduling of a C callback on the main interpreter thread *during* the …
> allow interruption of python code

- R/help.R
Previously: 
`reticulate::py_function_wrapper("tf$python$training$basic_session_run_hooks$StopAtStepHook")` gives:
```
#' 
#' 
#' @param num_steps num_steps
#' @param last_step last_step
#' 
#' @export
StopAtStepHook <- function(num_steps = NULL, last_step = NULL) {
tf$python$training$basic_session_run_hooks$StopAtStepHook(
num_steps = num_steps,
last_step = last_step
)
}
```
where description has been reassigned to empty string when extracting the preamble. 
After the fix:
```
#' Monitor to request stop at a specified step.
#' 
#' 
#' 
#' @param num_steps num_steps
#' @param last_step last_step
#' 
#' @export
StopAtStepHook <- function(num_steps = NULL, last_step = NULL) {
tf$python$training$basic_session_run_hooks$StopAtStepHook(
num_steps = num_steps,
last_step = last_step
)
}
```
> Fixed: class description consumed when extract preamble

- NEWS.md
- R/output.R
- R/package.R
- inst/python/rpytools/output.py
In R GUI the Python `sys.stdout` and `sys.stderr` are None (this may be an artifact of how stdout/stderr is handled/redirected for R GUI). This PR provides an R implementation of `sys.stdout` and `sys.stderr` when none exists.
> Provide sys.stdout and sys.stderr when they are None

- src/libpython.cpp
- src/libpython.h
- src/python.cpp
close #98
When a python environment is detected., we load `rpycall` module rather than to insert it into the initialization table.
> make reticulate work in an embedded python environment

- vignettes/arrays.Rmd
@kevinushey Could you take a look at this and let me know if it sounds correct?
@bwlewis We found that if you mixed NumPy reshaping and R reshaping in the same script (e.g. a tensorflow script that calls tf$reshape or np$reshape for training data, then R dim for prediction data) then the alternate ways of filling the reshaped array would cause problems. The `array_reshape()` function is intended to reshape R arrays in a manner consistent with NumPy.
A less hypothetical example would be a tensorflow model that was trained in Python (with reshaping of the raw input data) and then used in R (with dim based reshaping).
> add section to array vignette on reshaping

- R/knitr-engine.R
- tests/testthat/resources/example.Rmd
It looks like there was an off-by-one error wherein the final line of code in a Python chunk, if it did not produce any output, would not be emitted into the document.
Closes #126.
> ensure single lines of code emitted to document

- DESCRIPTION
- NEWS.md
- R/RcppExports.R
- R/package.R
- src/RcppExports.cpp
- src/libpython.cpp
- src/libpython.h
- src/python.cpp
When an R program using Python hangs, it is helpful to print the callstacks from the running threads every X milliseconds, this PR adds this functionality. Usage:
```r
Sys.setenv(RETICULATE_DUMP_STACK_TRACE = 1000)
reticulate::py_eval("1+1")
```
Output:
```
THREAD: []
THREAD: [<module> <module> compile _compile compile parse _parse_sub _parse _parse_sub _parse _parse_sub _parse _parse_sub _parse _parse_sub _parse _parse_sub _parse ]
[1] 2
```
> Add support to trace call stacks for python threads

- R/knitr-engine.R
- tests/testthat/resources/eng-reticulate-example.Rmd
- tests/testthat/test-python-knitr-engine.R
This PR implements support for a couple knitr chunk options (mainly prompted by #130). With this PR, we now have support for the boolean forms of `echo`, `eval`, and `include`.
> implement support for variety of chunk options

- R/knitr-engine.R
This PR opens up the reticulate engine a bit, providing the required endpoints for the RStudio IDE (or other front-ends) to hook in and handle various kinds of outputs produced by the engine.
This PR adds support for the following R options:
- `reticulate.engine.matplotlib.show`: Controls what happens when a `matplotlib` plot is shown;
- `reticulate.engine.wrap`: Controls how the generated list of outputs should be post-processed.
- `reticulate.engine.environment`: Controls what R environment is used for R <-> Python synchronization.
The intention is for the RStudio IDE to set these hooks to route console + plot output back to the Notebook cache, and display them in the IDE.
> allow configuration of reticulate engine

- R/knitr-engine.R
- tests/testthat/resources/eng-reticulate-example.Rmd
This allows Python chunk execution to continue when the `error=TRUE` chunk option is set, as is also done for R engines.
I believe this is still safe to take for the upcoming CRAN release (if that window is still open)
> support 'error=TRUE' for reticulate chunks

- inst/python/rpytools/help.py
This PR removes the implicit call to `func.__init__` and `func.__call__` when extracting docs for classes. Developers should instead just call `ClassName.__init__` explicitly instead. Otherwise, it's unclear which part of the generated docs belongs to which methods.
> Remove implicit doc extraction for Python classes

- R/completer.R
- R/repl.R
- R/utils.R
This PR implements a simple completer for the reticulate Python REPL, enabling completion for:
- Objects in the main module (at the top level),
- Object attributes (for completions following a `.`),
- Filesystem completions (within strings),
- Dictionary names (for e.g. `foo['ab`)
> implement simple completer for Python REPL

- vignettes/package.Rmd
This PR adds documentation related to the extensibility of conversion operators in the packages vignette, mainly letting users know that we handle conversion of builtin Python objects, NumPy arrays, and Pandas objects.
> document extensibility of conversion operators

- R/conversion.R
Use this if you want, but I wouldn't care if you weren't ready to support this yet! I figured it would be nice to at least support the conversion of a `DatetimeIndex` that has a time zone over to R. Right now these would just be stored as character rownames with the correct clock time, but a specialized `as.data.frame` for Pandas DataFrames could use this to correctly convert to a POSIXct `.index` column with the right time zone.
``` r
ex <- data.frame(
x = 1:10,
idx = as.POSIXct("2017-01-01", "UTC") + 0:9
)
ex_py <- r_to_py(ex)
ex_py_indexed <- ex_py$set_index('idx')
ex_py_indexed
#>                       x
#> idx                    
#> 2017-01-01 00:00:00   1
#> 2017-01-01 00:00:01   2
#> 2017-01-01 00:00:02   3
#> 2017-01-01 00:00:03   4
#> 2017-01-01 00:00:04   5 …
```
> Add DatetimeIndex conversion handling with timezone support

- R/generator.R
- pkgdown/_pkgdown.yml
This fixes the formatting of docs for `py_iterator` and moved `py_iterator` to "Python Types" section of the reference page. 
Originally (note the additional indentation before `g` and `generator` should be `py_iterator`):
```
sequence_generator <-function(start) {
value <- start
function() {
value <<- value + 1
value
}
}
g <- generator(sequence_generator(10))
```
The unrelated diff is probably because I am using the newer version of pkgdown (just did a fresh install from Github).
> Fixes for `py_iterator` doc

- R/use_python.R
If a conda env is not found,  `conda_env_python` is length 0 character instead of `NULL`.
```
> subset(conda_envs, conda_envs$name == condaenv)$python
character(0)
```
`use_condaenv` should fail now when `required = TRUE` and when the conda env is not found.
> Fixed issue with not failing use_condaenv when required but not found

- vignettes/calling_python.Rmd
@jjallaire Thanks for the edits! It reads much better now! Just fixing two typos here.
> Fix typos in calling_python.Rmd

- R/repl.R
It looks like this boolean has been documented in reverse. `quiet=TRUE` suppresses the banner (which makes sense). This edit just corrects that.
> Update help for `quiet`

- R/install.R
- man/py_install.Rd
This allows users to pass additional arguments, such as `ignore_installed`, `pip`, etc.
> Allow to pass additional args to install method

- R/conversion.R
This PR seeks to fix the issue raised in https://github.com/rstudio/reticulate/issues/244, that reticulate fails to convert pandas DataFrames where a column name matches a DataFrame method.  
The change is to use ``x$`__getitem__`(column) `` instead of `x[[column]]` within py_to_r.pandas.core.frame.DataFrame method.  This avoids `x[[column]]` being converted to `x.column`.  Accessing a column as an attribute fails when the column name clashes with a pandas method, as described in [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access)
> address issue with pandas DataFrame names that clash with DataFrame methods

- R/conversion.R
When I first implemented the index handling for the conversion from Py DataFrames to R data.frames, I was using an older version of pandas (Something around 0.20.1). Since then, they reworked the top level libraries, see [here](https://pandas.pydata.org/pandas-docs/version/0.20/whatsnew.html#reorganization-of-the-library-privacy-changes). I just updated pandas recently and found that out. This changed the actual class of the index. 
For ~0.20.1
``` r
pd <- import("pandas", convert = FALSE)
rng = pd$date_range("2011-01-01", periods=2L, freq='H', tz = "UTC")
class(rng)
#>  [1] "pandas.core.indexes.datetimes.DatetimeIndex"           
#>  [2] "pandas.core.indexes.datetimelike.DatelikeOps"          
#>  [3] "pandas.core.indexes.datetimelike.TimelikeOps"          
#>  [4] …
```
> Add "new" pandas index types for catching DataFrame index column conversion

- R/python.R
This PR fixes the unhelpful error message seen in https://github.com/rstudio/keras/issues/400#issuecomment-388769194.
The issue there was our attempt to fall back to item access from attribute access ended up emitting a `getitem`-related error, which is rather confusing in that context. The fix here is to ensure that (by default) `$` only accesses attributes.
Note that Python dictionaries still have their own `$` operator that allow item access, and Pandas DataFrames own `__getattr__` falls back to items when no such attribute exists in their own implementation.
> don't call __getitem__ for '$'

- R/conversion.R
This PR makes two changes:
- `py_to_r()` now tags the returned R data.frame with the Pandas index, as an attribute called `pandas.index`. This is for users who need to post-process the index in some way, because our default converter didn't do the right thing.
- We detect duplicate values in the index; when discovered, we don't attempt to set the index and instead emit a warning.
Fixes https://github.com/rstudio/reticulate/issues/270.
@jjallaire let me know if this feels like the right change.
> handle duplicates in Pandas index

- R/conversion.R
- tests/testthat/test-python-pandas.R
This PR ensures that we convert non-string names to strings (using `format()`) when converting Pandas DataFrames.
> handle complex names (#274)

- NEWS.md
- src/libpython.h
- src/python.cpp
- tests/testthat/test-python-numpy.R
This PR fixes #280 by converting the (`int`-flavored) R logical vector into a plain array of `bool`s before creating the NumPy array.
We set the `NPY_ARRAY_OWNDATA` flag to tell NumPy that it should own + manage the data passed in to the constructor when doing this, so that Python / NumPy itself can free the malloc'ed data when the associated Python object goes out of scope.
> fix conversion of boolean matrices (closes #280)

- NEWS.md
- src/python.cpp
Addresses https://github.com/rstudio/reticulate/issues/298 
@kevinushey Could you review this please?
I'm wondering if the `static` references I introduced to the R reticulate environment and `r_to_py()` functions could cause any problems? (e.g. being feed at the end of a process lifetime when R is already gone?).
The other issue is ensuring that we have all of the memory semantics right (i.e. we won't either leak objects or leave an object without a reference causing a crash). This is about the lowest level change we could make in reticulate so has the potential to wreak havoc if it's not done correctly!
> Always call r_to_py S3 method when converting objects from Python to R

- DESCRIPTION
- NEWS.md
- R/python.R
Same behavior as Python. See https://stackoverflow.com/questions/6432355/variable-defined-with-with-statement-available-outside-of-with-block
@kevinushey Could you review this?
cc @skeydan re: https://github.com/rstudio/tfsandbox/issues/4
> Make variables defined using %as% operator in with() available after execution of the with block

- R/output.R
- inst/python/rpytools/output.py
Fixes https://github.com/rstudio/reticulate/issues/313.
@jjallaire can you review? I wonder if the intention was that this code would be firing more often (it seems like Python is always initialized with `stdout` and `stderr` but we might want to remap to R in those cases as well)
> always remap output streams with Windows + Python 2.7

- R/config.R
- R/knitr-engine.R
Fixes #296.
The issue here: in Anaconda environments, `matplotlib` will see that Qt libraries and supporting packages are available, and select a Qt backend as the default backend to use for plots. Unfortunately, attempting to do so within RStudio will then fail due to the difference in versions between Qt used by RStudio and Anaconda.
To fix this, we enforce the default `agg` backend when this specific combination is detected.
> attempt to disallow Qt-based matplotlib backends

- R/knitr-engine.R
Fixes an issue noted by https://github.com/rstudio/rstudio/issues/1556#issuecomment-410789560.
Putting this up as a PR as I do not recall the original motivation for stripping these blank lines, but it seems it was done very early on (https://github.com/rstudio/reticulate/commit/93886117f4f414cb1b88d7932071d9e3b4ddbae7).
I don't seem to notice any ill effects from including the blank lines (and they are then properly reflected in the resulting rendered document) so I think this should be safe.
> don't drop blank lines in reticulate engine

- NEWS.md
- R/knitr-engine.R
- R/repl.R
- R/utils.R
- tests/testthat/resources/eng-reticulate-example.Rmd
This PR fixes an issue where running a chunk e.g.
`````
```{python}
1 + 1
```
`````
would not produce any output when run in RStudio. Note that the execution model here is effectively the same as what we do in `repl_python()`; ie it uses the same tricks to ensure that Python auto-prints the evaluated expressions.
> ensure code is auto-printed in Python chunks

- R/config.R
- R/package.R
- R/use_python.R
- R/virtualenv.R
- tests/testthat/resources/venv-activate.R
- tests/testthat/test-python-virtual-environments.R
This PR is the first step in support for Python virtual environments created by `venv`.
Note that these virtual environments are almost identical to those created with `virtualenv`. The only difference is that the `activate_this.py` script is missing. My understanding is that `activate_this.py` is a hack that tries to allow an existing Python session to bind to an existing virtual environment; whereas the preferred route is to instead run e.g.
source bin/activate && python
which works as expected for virtual environments created by both `virtualenv` and `venv`.
Something we should discuss then is whether we need any other code changes to support virtual environments that don't contain this script. I see we use it at e.g.
https://github.com/rstudio/reticulate/blob/93c9ee9bceee360a9aa3a43173 …
> detect virtual environments created with venv

- R/config.R
- R/package.R
In some Linux distributions such as Centos 7, Python library is only available as `libpython2.7.so.1.0` (if `python-devel` package is not installed). This patch ensures that these library files are found.
Related issue: https://github.com/rstudio/reticulate/issues/291#issuecomment-424299557, https://github.com/rocker-org/rocker/issues/296 .
> Search for any unconventional Python library extensions in Linux

- DESCRIPTION
- R/pip.R
- R/python-tools.R
- R/virtualenv.R
- man/virtualenv-tools.Rd
This PR revamps the internals around how Python virtual environments are created + used in reticulate.
Primary goals here:
1. Refactor the existing code, as it was getting a bit difficult to manage;
2. Create a separate `pip` interface that can be used internally for installing / removing packages,
3. Better handle the nuances between `virtualenv`, `venv`, and where they might (might not) be available for different Python installations.
One major change this PR makes: we now attempt to use `virtualenv` and `venv` as modules whenever possible. This avoids some potential ambiguities -- for example, when one sees a `virtualenv` executable on the PATH, it's hard to ascertain which Python installation it's actually associated with, and in general it's safer to use Python x.y.z to create a …
> revamp python virtualenv helper internals

- NEWS.md
- R/help.R
- tests/testthat/test-help-handlers.R
This PR allows us to extract the arguments associated with Python builtin functions, by parsing the provided function signature. (For most Python builtin functions, the first line in the documentation gives the prototype of the function)
This code is a port of the code currently used in RStudio for autocompletion so this is just syncing up the two pieces that diverged a bit over time.
> parse function arguments from docs when needed

- R/knitr-engine.R
- R/utils.R
- tests/testthat/resources/eng-reticulate-example.Rmd
This PR implements auto-printing of matplotlib plots, when the last statement within a chunk produces a matplotlib object of some kind. Works in the IDE as well as in rendered documents.
Closes https://github.com/rstudio/rstudio/issues/4167.
> implement auto-printing of matplotlib plots

- R/package.R
Set environment variable before initializing Python (see https://github.com/rstudio/reticulate/issues/208#issuecomment-462089957). Also linked to issue #98 (use environment variables to track initialization state).
> Set env variable before initialization

- DESCRIPTION
- src/python.cpp
Fixes https://github.com/rstudio/reticulate/issues/437. For whatever reason, the use of a local dict causes some issues with name resolution when attempting to source `activate_this.py`.
> avoid use of local dict (#437)

- .travis.yml
Currently [test-python-scipy-sparse-matrix.R](https://github.com/rstudio/reticulate/blob/master/tests/testthat/test-python-scipy-sparse-matrix.R) is skipped if `scipy` is not installed. Given that this feature is being used by other projects, we should test this at least on Travis to make sure it always works.
> Add scipy installation on Travis

- R/config.R
- R/package.R
- R/utils.R
- R/virtualenv.R
- tests/testthat/test-python-knitr-engine.R
Closes #367.
The fix here effectively moves some of the PATH modification we do to before the attempt to discover the Python configuration + load numpy.
There's a bit of extra orchestration required here as we don't want the PATH changes to persist if we're only attempting to discover Python; ie, we only want to save the PATH changes if we're truly initializing Python. I think I got the semantics right here but it's worth double-checking that I'm doing things correctly.
> modify PATH before discovering Python config

- R/conda.R
This is a fix for https://github.com/rstudio/keras/issues/691 that basically re-routes a request to use `condabin/conda` back to `bin/conda`, as the required conda utilities (e.g. `activate`) are only installed in that `bin` folder.
Note that making this change in `reticulate` does fix the issue in `keras` since it relies on `conda_binary()` to resolve the path to `conda`.
> prefer bin/conda to condabin/conda

- R/conda.R
- R/config.R
- R/install.R
- R/use_python.R
- R/utils.R
- R/virtualenv.R
- man/conda-tools.Rd
- man/py_install.Rd
- man/virtualenv-tools.Rd
This PR implements the notion of a 'default' Python environment, as managed through the `RETICULATE_PYTHON_ENV` environment variable. The idea is that all of the various functions `virtualenv_create()`, `py_install()`, `conda_install()` and so on would use this environment by default if `envname = NULL` (the default) and the aforementioned environment variable is set.
> implement notion of 'default' env for python actions

- NEWS.md
- R/conversion.R
- tests/testthat/test-python-datetime.R
Closes #458.
@jjallaire I think my error here was passing along the `convert` argument during the imports of the `datetime` module, when (if I understand correctly) it's normally used for the Python capsules and especially for handling conversion of R functions. Let me know if this change looks right to you.
> fix for conversion of date objects

- NEWS.md
- R/conversion.R
Fixes the issue described in https://github.com/rstudio/keras/issues/732.
I wanted to add a unit test for this behavior but for the life of me couldn't produce a a standalone example that exhibits the same behavior :/
> don't disable convert when converting lists

- src/libpython.cpp
- src/libpython.h
This fixes the crash in #487 when numpy is not in the search path. This is a new issue after upgrading to python 3.7, so there might be other occurrences (although I didn't see anything specific in the changelog).
> Fix crash on failed numpy import

- R/config.R
- R/python-tools.R
It seems that Windows in R3.6 using system2 call, does not return a stdout from an python call. It seems to me that it only returns data as stderr. Therefore py_config() does not return the configuration from the python file. It provides configuration detail only in stderr and not in stdout. This leeds the an mapply error, because the config is only of length=0. 
See also issue: https://github.com/rstudio/reticulate/issues/498
Additional python_version and python_module_version in python-tools.R use also the system2 command. 
I have changed those calls in my fork and it seems now it's working on my PC, maybe someone can check if this solution is a possible solution for the whole package or if there is a bug which should be corrected in R 3.6
> R3.6 Windows Problems with reticulate

- R/conversion.R
- inst/python/rpytools/test.py
- tests/testthat/test-python-lists.R
Before modifying `test.py` I tried this R-only test 
```
builtins <- import_builtins(convert = FALSE)
collections <- import("collections", convert = FALSE)
t <- builtins$tuple(list(22, collections$OrderedDict(list(list(777, "b"), list(1, "a")))))
py_to_r(t)
```
but this didn't convert the ``OrderedDict``:
```
[1]]
[1] 22
[[2]]
OrderedDict([(777.0, 'b'), (1.0, 'a')])
```
> recursively convert tuples as we do lists

- R/conda.R
On Windows we are seeing the following error when using `conda_create` on a clean installation (see https://github.com/rstudio/tensorflow/issues/325 )
```
> reticulate::conda_create(envname = "test")
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: ...working... failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/msys2/noarch/repodata.json.bz2>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\' …
```
> SSLError when installing

- R/python.R
This PR allows clients of `reticulate` to register hooks that get run when a module is loaded. This can be useful for e.g. front-ends that need to take some action in response to a module of interest being loaded.
One motivating example is with `matplotlib.pyplot`. One might want to override the `show()` method, so that the plot is shown in a custom way (e.g. in RStudio, shown in the Plots pane). Having an import hook would make it possible to ensure that code of this form:
```R
matplotlib <- import("matplotlib")
plt <- import("matplotlib.pyplot")
plt$plot(1:5, 1:5)
plt$show()
```
would work without issue.
Note that this is different from the existing delay_load system -- that allows the user themselves to register hooks that get run when their module is loaded; in our …
> implement mechanism for module load hooks

- .travis.yml
- R/conda.R
- R/install.R
- R/python-tools.R
- R/virtualenv.R
- man/py_install.Rd
- tests/testthat/helper-utils.R
- tests/testthat/resources/venv-activate.R
- tests/testthat/test-py_func.R
- tests/testthat/test-python-virtual-environments.R
Closes #543.
This PR makes the following changes:
- When type is "auto", we try to detect and infer the environment type directly if an envname was supplied.
- `python_unix_binary()` is removed, and we now instead query `RETICULATE_PYTHON` as well as the PATH for the version of Python to use when creating a new virtual environment. This is done in the `virtualenv_default_python()` function. (note that this detection is not required for Conda environments)
Effectively, this takes some of the logic that was inlined in `py_install()` and delegates back to the already-existing `virtualenv_` and `condaenv_` functions for accomplishing the same.
> revamp py_install()

- NEWS.md
- R/config.R
- src/libpython.cpp
- src/libpython.h
- src/python.cpp
This is a simpler version of #546, which simply allows the user to choose between debug / release versions of Python at compile time for reticulate. The user can define `RETICULATE_PYTHON_DEBUG` to declare that they're building a version of reticulate that should work with debug versions of Python.
This is less useful than #546, but safer, and since this is already a feature intended for 'expert' users it's probably okay to hide it behind a pre-processor define (ie I imagine we'd only use this internally when attempting to debug crashes / segfaults)
> allow reticulate to be compiled to use debug Python

- R/conda.R
- R/install.R
- R/python-environments.R
- R/utils.R
- R/virtualenv.R
- man/conda-tools.Rd
- man/py_install.Rd
- man/virtualenv-tools.Rd
This PR allows users of `py_install()` and `conda_install()` to request a specific Python version, to be installed in the associated Conda environment. (it currently ignored for virtual environments)
This should allow e.g. `install_tensorflow()` to work with Conda environments with a specific Python version requirement.
> accept 'python_version' in py_install()

- src/python.cpp
@kevinushey I am getting some random crashes with TF nightly and this fixes it. 
I am not really sure why this happens, but can be related on how the TF autograph creates and calls functions that we define.
I once proposed this fix: https://github.com/rstudio/reticulate/pull/520 but I think this one is more precise.
The easiest way to reproduce the segfault is to install TF nightly and run :
```
tfdatasets::dataset_map(tfdatasets::tensors_dataset(1:10), function(x) x)
```
Although the error happens whenever you pass R functions to TensorFlow.
> check if keywords are NULL before trying to do anything

- R/conda.R
Older versions of Conda can return an empty list of environments which causes an error when calling `normalizePath`. Eg. `normalizePath(list())`.
This happens mostly in AppVeyor, since multiple versions of conda are installed by default.
> invalid 'path' argument when no environments are found by conda -info

- R/RcppExports.R
- R/python.R
- src/RcppExports.cpp
- src/python.cpp
- tests/testthat/test-python-function.R
I’m not very experienced in Rcpp *or* Python’s C API, but I’m there I think!
This PR converts signatures in a compatible way.
1. Defaults are all set to `NULL` for the time being. This can be improved in a further PR, but isn’t super important, as it doesn’t matter for autocompletion (as R and RStudio autocomplete `paramname = ` for you and therefore ignore that information).
2. `...` in R replaces `*args` and `**kw` at once, so the first occurrence of either is replaced by `...` in the formals.
3. R doesn’t support positional-only parameters such as x and y here. So e.g. the suggestions for `pow` will be wrong:
```r
> builtins$pow(<tab>
| x =    
| y =    
| z =    
> pow(x = 2, y = 2)
Error in py_call_impl(callable, dots$args, dots$keywords):
TypeError: pow() takes no keyword arguments …
```
> Autocomplete functions: Get formals from Python function signatures!

- R/package.R
- R/python-packages.R
- R/python-tools.R
NOTE: not yet ready for merge; putting this up as a PR just to further facilitate discussion.
---
This PR intends to make it possible for R packages to declare their reticulate Python requirements, and to have `reticulate` automatically discover and install those declared dependencies when using a Miniconda environment.
The intention is that users will be able to run R packages that act as wrappers to Python packages with minimal overhead; that is, they will not need to worry about Python environment management, as `reticulate` will take care of that automagically.
R packages can declare the packages they require with a new field in the DESCRIPTION file. For example, a package wrapping TensorFlow might use:
```
reticulate@R: list(
list(package = "tensorflow", pip = TRUE),
list(package = …
```
> initial work on python dependency discovery + install

- R/RcppExports.R
- R/conversion.R
- src/RcppExports.cpp
- src/libpython.cpp
- src/libpython.h
- src/python.cpp
- tests/testthat/test-python-pandas.R
Purpose: Convert `pandas` dataframes on c++ level instead of in R, to reduce number of round trips.
This is just to show the general approach; in this initial version, the only "non-automatic" data type (meaning, the only one for whom calling `py_to_r` will not be sufficient) is `pd.Categorical`. More data types will need specific handling.
I could also imagine that we'd want to split out these individual functions, and/or add them as branches to `py_to_r`?
Thanks for taking a look :-)
> WIP: py_convert_pandas_df

- src/libpython.cpp
- src/libpython.h
- src/python.cpp
This is just the first step reg. `Py_CompileString`, Python is successfully loaded for Python 3.9 (including 3.8 ... 3.2 - `Py_CompileStringExFlags` was added in 3.2)  as well as Python 2.7 now. 
But I haven't yet found a way to use the adequate function in `py_eval_impl`:
dummy code:
```
if (FALSE)
compiledCode(Py_CompileString(code.c_str(), "reticulate_eval", Py_eval_input));
else 
compiledCode(Py_CompileStringExFlags(code.c_str(), "reticulate_eval", Py_eval_input, NULL, 0));
```
I was searching for  a way to check if a function exists in cpython, but haven't found one yet... (tried e.g. to see if the module dict from `main` has a key with that name)
Just copying the macro from 
https://github.com/python/cpython/blob/da6ce58dd5ac109485af45878fca6bfd265b43e9/Include/pythonrun.h#L99-L103 …
> WIP: Python 3.9 compatibility

- R/conda.R
- R/miniconda.R
- R/pip.R
- R/python-packages.R
- R/utils.R
- R/virtualenv.R
- man/conda-tools.Rd
- man/configure_environment.Rd
- man/py_function_custom_scaffold.Rd
- man/py_function_wrapper.Rd
- man/virtualenv-tools.Rd
- vignettes/python_dependencies.Rmd
This PR makes it possible for R packages to declare specific versions of Python dependencies. R packages can hence declare e.g.
```
reticulate@R:
list(
packages = list(
list(package = "scipy", version = "1.3.0")
)
)
```
to indicate that the package depends on `scipy [1.3.0]`.
---
> allow packages to declare specific versions of dependencies

- R/class.R
- tests/testthat/test-python-class.R
This PR fixes https://github.com/rstudio/keras/issues/926#issuecomment-554489312
so the user doesn't need to manually convert arguments to R types kin order to use them in methods.
> Convert arguments to R types before passing to the method.

- R/class.R
- tests/testthat/test-python-class.R
This PR enables the convert scope for the `self` instance, fixing: https://github.com/rstudio/reticulate/pull/655#issuecomment-558236772
**Pending adding tests**
> Enable the convert scope for the self instance.

- R/python.R
- returns completions matching pattern, allowing tab completion in
vanilla R
Previously:
```
> import("numpy") -> numpy
> str(.DollarNames(numpy, "a"))
chr [1:587] "abs" "absolute" "absolute_import" "add" "add_docstring" ...
- attr(*, "types")= int [1:587] 6 6 4 6 6 6 6 5 6 6 ...
- attr(*, "helpHandler")= chr "reticulate:::help_handler"
> numpy$a<tab>
> numpy$a
```
After PR, in vanilla R
```
> numpy$array2string numpy$array_equiv  numpy$array_split
> str(.DollarNames(numpy, "a"))
chr [1:264] "abs" "absolute" "absolute_import" "add" "add_docstring" ...
- attr(*, "types")= int [1:264] 6 6 4 6 6 6 6 6 6 6 ...
- attr(*, "helpHandler")= chr "reticulate:::help_handler"
> numpy$a<tab>
numpy$abs               numpy$apply_over_axes   numpy$array_equal
numpy$absolute          numpy$arange …
```
> .DollarNames(x, pattern) obeys its contract

- src/python.cpp
> Implement r_to_py for external pointer

- R/package.R
- R/python-packages.R
I am not totally sure what we want to do here... (long-term)
On the one hand, in the recent blog post we say 
> Currently, automatic Python environment configuration will only happen when using the aforementioned reticulate Miniconda installation.
On the other hand, we do have an escape hatch in place already (RETICULATE_AUTOCONFIGURE) so we could as well leave the default as is... and remove the comment 
https://github.com/rstudio/reticulate/blob/c403546661ee7f8273ff505a8cd4f4ec6e2bfa8e/R/python-packages.R#L4
instead (and update the blog post I guess)...
Sorry I didn't "really" check this out before (though I could have, as I'm in the have-to-opt-out situation for virtualenv all the time...)
> don't force as this would apply to non-miniconda-envs as well

- R/class.R
- tests/testthat/test-python-class.R
This fixes a bug when creating a third level of inheritance with classes created from R. 
The problem is this line:
https://github.com/rstudio/reticulate/compare/master...dfalbel:fix-inheritance?expand=1#diff-9603c58bdf50909f0162edee456f1ef6L12
Turns out this is a common bug in python, see: https://stackoverflow.com/a/17509938/3297472
I also added a test that shows the bug if you run with the current reticulate version.
> Fix multiple inheritance

- R/wrapper.R
This should be extracting from `docs$parameters` instead of `docs$sections`.
> Fix incorrect extraction of parameter descriptions

- NEWS.md
- R/package.R
- R/python-packages.R
- man/configure_environment.Rd
Otherwise, packages configuring Python with e.g.
```
.onLoad <- function(libname, pkgname) {
reticulate::configure_environment(pkgname)
}
```
could inadvertently attempt to configure a system copy of Python.
> ensure configure_environment() is noop if using 'system' Python

- R/knitr-engine.R
This is my attempt to fix issue [#706](https://github.com/rstudio/reticulate/issues/706).
For functions with decorators, Python 3.8 updated `lineno` to point to the `lineno` of the `def`, rather than the `lineno` of the first decorator (see [this PR](https://github.com/python/cpython/pull/9731)).
I updated the code that extracts line numbers to use the first decorator's `lineno` if available, and otherwise the node's `lineno`. Unsure if this is the best approach, so I appreciate any feedback, but it appears to work.
> fix #706 handling of lineno with decorators

- R/knitr-engine.R
- R/utils.R
I've implemented the functionality described in [#717](https://github.com/rstudio/reticulate/issues/717). Adding a trailing semicolon stops return values from being output.
> suppress output with semicolon (fix #717)

- R/package.R
Previous error message erroneously pointed to the wrong vignette.  The `python_packages` vignette is about installing packages whereas the `python_dependencies` is the right resource for package developers who depend on reticulate functionality.
> Point to proper vignette that details package developer tips

- R/conda.R
- man/conda-tools.Rd
- tests/testthat/test-python-envs.R
This PR adds the arguments `forge` and `channel` to `conda_create` analogously to how they work in `conda_install`.
This is a tiny PR, but adding these arguments will change behavior for two reasons:
- I set the default value for `conda` to `TRUE` just like for `conda_install`. Previously, it would just use whatever the user had configured conda to do (see `conda config --show-sources`)
- I'm squeezing the `forge` and `channel` arguments in before the `conda` argument just like for `conda_install`.
I also added a tiny test for this. But to make the test meaningful I need to access the channel of installed packages somehow (ideally without activating the conda environment). So I amended `conda_list_packages` to also return a column with the `channel` just like you see when you run `conda …
> Allow specifying channel in conda_create

- R/install.R
The reason for this change is described below. However, I'm not sure if there are any unintended consequences in other usage scenarios, so this PR is kind of tentative :-)
Reason:
When you have RETICULATE_AUTOCONFIGURE set to`0`, but execute (or have other packages execute) `py_install()` right at the start of a session - meaning that `is_python_initialized()` yields `FALSE` - `reticulate` will try installing into an env called `r-reticulate`, even though `py_config()` would have correctly discovered the one you specified by `. ~myenv/bin/activate` before starting RStudio.
This PR makes sure Python is always initialized  before `py_install` is called.
> initialize before py_install

- pkgdown/_pkgdown.yml
I noticed that this existed but was not in the menu
> Add python_dependencies vignette to header menu

- R/repl.R
- R/utils.R
The output of the following python code in `repl_python()` will be buffered until the whole block is done.
```py
import time
for i in range(10):
print(i, flush = True)
time.sleep(1)
```
It is because `py_compile_eval` has captured the output. This PR adds an option to `py_compile_eval` so that the output is not captured.
Before:
After:
related to https://github.com/rstudio/reticulate/issues/739#issuecomment-637374290
> do not capture output in repl mode

- NEWS.md
- R/conda.R
- man/conda-tools.Rd
This PR makes miniconda prefered (if installed) over system conda installation. Fix #786
> Prefer miniconda

- R/conda.R
- R/config.R
- R/python-tools.R
This PR adds 3 fixes:
1. On Windows it won't identify the root conda path as a virtualenv by checking if  `!file.exists("condabin/conda")`.
2. It ignores the root conda environment as a possible environment in `conda_list` by checking if it's path is equal to the `root_prefix` returned by `conda info`. This environment is not correctly writable.
3. If users opts out for miniconda, they can still have a fresh conda installation that don't have any environment. (conda is installed, but no environment is available). In this case we create an `r-reticulate` environment.
It fixes #789
> Check for a conda installation before prompting for miniconda

- NEWS.md
- R/config.R
- R/package.R
- R/virtualenv.R
- inst/config/config.py
This PR fixes a couple issues:
1. In some cases, virtual environments are created only with a copy of the Python interpreter, not the Python shared library. In such a case, we need to use the copy of Python that was used to create the virtual environment, and bind to that shared library instead.
2. In some cases, `reticulate` would fail to initialize Python as certain system modules could not be found. See e.g. https://stackoverflow.com/questions/5694706/py-initialize-fails-unable-to-load-the-file-system-codec. The solution here is to set `PYTHONPATH` based on what the interpreter would use as `sys.path`, so Python can resolve these system modules properly.
> set PYTHONPATH before initializing Python

- DESCRIPTION
- NEWS.md
- R/import.R
- R/python.R
- inst/python/importhook/LICENSE
- inst/python/importhook/__init__.py
- inst/python/importhook/finder.py
- inst/python/importhook/loader.py
- inst/python/importhook/logger.py
- inst/python/importhook/meta_paths.py
- inst/python/importhook/registry.py
- inst/python/importhook/tests/test_meta_paths.py
- inst/python/importhook/utils.py
- inst/python/rpytools/loader.py
- tests/testthat/helper-init.R
- tests/testthat/resources/.gitignore
- tests/testthat/test-aaa.R
- tests/testthat/test-python-knitr-engine.R
This PR fixes an issue where modules imported recursively in response to other modules being loaded would not have R load hooks fired.
> use 'importhook' module for robust module load hooks

- R/generator.R
- tests/testthat/test-python-iterators.R
Fixes a typo in the validation of formals.
```r
py_iterator(function(x) x)
#> Error in formals(fn) != 0 :
#>   comparison (2) is possible only for atomic and list types
```
Becomes
```r
#> Error in reticulate::py_iterator(function(x) x) :
#>   fn must be an R function with no arguments
```
> Fix formals check in `py_iterator()`

- README.md
- docs/index.html
- index.Rmd
It has been moved to travis-ci.com instead of travis-ci.org.
> Update link to Travis build

- R/package.R
it is needed for R embedded in python because the `PYTHONPATH` trick no longer works.
related #208
> insert path to rpytools for embedded R

- R/knitr-engine.R
Fix #993: `engine_output()` has been exported in knitr a couple of years ago, so no need to use the internal `knitr:::wrap()`.
> Use knitr::engine_output() instead of knitr:::wrap()

- R/miniconda.R
This follows a regression after https://github.com/rstudio/reticulate/commit/9cf3178d344c6ed61e9648127038c020f1228a60
Miniconda urls are not using `-` but `_`: https://repo.anaconda.com/miniconda/
It was first reported by @topepo from https://github.com/tidymodels/parsnip/runs/2726912897?check_suite_focus=true#step:9:41
I can reproduce on Windows with last dev version 
````r
> install_miniconda(force = TRUE)
* Downloading "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86-64.exe" ...
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86-64.exe'
Error in download.file(url, destfile = installer, mode = "wb") : 
cannot open URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86-64.exe'
In addition: Warning message:
In download.file(url, …
```
> miniconda installer url uses x86_64 and not x86-64

- R/config.R
added on.exit(add=TRUE) so that this call can coexist with the
other on.exit calls in the same frame.
> restore LD_LIBRARY_PATH on linux

- R/miniconda.R
Added options `reticulate.miniconda.url` to allow users to specify where to download miniconda, to install conda from intranet, conda-forge or personal repos. 
This quick fix solves #1012 #1019.
> Allow conda to be installed from customized place

- NEWS.md
- R/conda.R
- R/config.R
- R/pip.R
when attempting to run `tensorflow::install_tensorflow()` in RStudio on Windows, this error message can pop up:
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't …
```
> inject PATHs when using pip in condaenv

- R/conda.R
- R/pip.R
Manually implements the equivalent of `conda run`, as a workaround for https://github.com/conda/conda/issues/10972
Partially reverts https://github.com/rstudio/reticulate/pull/1053
Restores `keras::install_keras()` failing tests: https://github.com/rstudio/keras/actions/runs/1317897279
> add conda_run2()

- R/miniconda.R
`miniconda_installer_arch` currently does not have access to the variable `info` which causes the error 
`Error: Error in miniconda_installer_arch() : object 'info' not found`
> fix install_miniconda

- NEWS.md
- R/miniconda.R
Right now, `install_miniconda()` fails at the `r-reticulate` environment creation step on an M1 Mac.
This is because the minimum (native Arm) python version available from `conda` is 3.8. 
Rather than installing different python versions on Arm Macs vs other platforms, I think it's better to bump the python version everywhere. 
There is also a case to be made for bumping to python 3.9, since that's the default python version that comes with miniconda, (meaning, smaller overall install and less to download).
> bump miniconda default python version to 3.8

- R/conda.R
- R/config.R
Follow up to #1083
cc: @cderv.
Note, even with this fix, binding to the Python installed from the Microsoft Store fails for me, albeit for a different reason now.
Now I get this error message:
```
Error in py_initialize(config$python, config$libpython, config$pythonhome,  :
C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0/python39.dll - Access is denied.
Calls: print ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
In addition: Warning message:
In file.info(x, extra_cols = FALSE) :
cannot open file 'C:\Users\kalin\AppData\Local\Microsoft\WindowsApps\python.exe': The file cannot be accessed by the system
Execution halted
```
After some googeling this appears to be not easily resolvable: …
> Fix binding to system python

- R/import.R
resolves the issue reported in #1058, where the (recomended) value of `TRUE` would cause errors. 
The fix is a bit ugly, as reticulate is now resolving single arguments to a list in `import_from_path_delayed`, and spreading that list back out to single arguments in `import` itself. Some refactoring might be in order, but I don't feel confident enough to make more sweeping changes. 
I aimed to cover the documented options for `delay_load` (function, list and boolean), and fail early for other inputs.
> resolve non-list values for `delay_load` in `import_from_path_delayed`

- DESCRIPTION
- R/install.R
- man/py_install.Rd
in `py_install()`, respect both `pip_ignore_installed` and `ignore_installed`, in both conda and virtualenv python installations.
> Streamline ways to invoke `pip --ignore-installed` in `py_install()`

- NEWS.md
- R/install-python.R
- R/use_python.R
- R/zzz.R
- man/use_python.Rd
This PR makes `use_python()` and friends use `required = TRUE` by default.
For packages calling `use_*()` APIs in their `.onLoad()` hooks, we default to `FALSE` (as per the old behavior) just to reduce the chances of breaking backwards compatibility.
> use 'required = TRUE' by default

- R/RcppExports.R
- R/python.R
- man/py_len.Rd
- src/RcppExports.cpp
- src/python.cpp
This PR ensures that `length.python.builtin.object()` always returns a numeric value, in line with what users would normally expect from the `length()` generic.
`py_len()` continues to emit an error for Python objects without a defined length.
> ensure length() returns a numeric value

- .github/workflows/pkgdown.yaml
This is required to enable examples and vignettes to run.
> create r-reticulate venv in pkgdown GHA runner

- NEWS.md
- R/python-tools.R
This pull request addresses #1149. 
I have refactored the `python_info_condaenv_find()` method to handle spaces within the file paths returned from the `conda-meta/history` file. This allows me to call `use_condaenv()` on my ArcGIS Pro installation of conda, but this approach should also work for other installations with non-standard file paths. 
Before these changes were made I would see this error:
```r
use_condaenv(condaenv = "arcgispro-py3-clone", conda = "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/Scripts/conda.bat", required = T)
use_condaenv(condaenv = "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone", required = T)
```
With the proposed changes, I'm now able to load the correct conda env without any issues:
```r
use_condaenv(condaenv = …
```
> refactor `python_info_condaenv_find()` to handle spaces in file paths when parsing `conda-meta/history`

- DESCRIPTION
@t-kalinowski R does not seem to support comma's in the name it self.
> Fix typo in maintainer details

- NEWS.md
- R/conda.R
- R/pip.R
- R/utils.R
- R/virtualenv.R
Tracing python environment management commands for two reasons:
1. Help users self-diagnose issues like, the wrong python or conda being found and arguments being improperly quoted, which should result in fewer issues filed. Then for issues that are filed, we should be able to easily identify the exact system command that's failing.
2. Educate users about what reticulate is doing. This will give newbies a foothold on understanding the mechanics of python environment management, and give experienced users confidence that reticulate is doing the "right thing".
> trace python env management commands

- R/use_python.R
I have reported the issue #1167 
In previous versions of reticulate it was possible to call use_python with the directory of the python binary without including the executable. This was tested in Windows. 
In newer versions (at least 1.24) this no longer works. This is due to calling `python_config_impl` with the 'unnormalized' path. Previously, the path has been normalized before proceeding further in the code. 
With this change, the given python path within `use_python` is normalized before working with it. This should restore the previous (undocumented) behavior of `use_python("C:/Users/dummy/Documents/R/win-library/4.1//extdata/python")` which currently prompts an error like:
**Error in system2(command = python, args = shQuote(script), stdout = TRUE, : …
> Paths used in 'use_python()' are now normalized before being used to configure Python

- .github/workflows/R-CMD-check.yaml
Follow NEP29[1], the de facto standard of the scientific python ecosystem,
for supported versions, but more backwards compatibility could be added.
1: https://numpy.org/neps/nep-0029-deprecation_policy.html
> Run CI against several explicit python versions

- R/conda.R
Fix #1189
Not all conda installations have a 'conda.bat' entry point. 
Some Python installations, like the one that ESRI ships with ArcGIS Pro, only have an activate.bat.
This patch finds and prefers 'activate.bat' in `conda_run2` on windows.
> prefer 'activate.bat' on windows conda

- NEWS.md
- R/install-python.R
- R/pyenv.R
- man/install_python.Rd
+  Run `pyenv update` as part of installing pyenv on windows (the default list of Python versions it ships with is outdated)
+  Better error message if user requests an unavailable version like `install_python("3.13:latest")`
+  Bump default arg in `install_python()` from "3.8:latest" to "3.9:latest", because 3.8 fails to build on M1 Macs.
+  Implement internal utility `pyenv_update()`
> Minor pyenv tweaks

- R/RcppExports.R
- R/python.R
- src/RcppExports.cpp
- src/python.cpp
This patch fixes https://github.com/rpy2/rpy2/issues/872, and is a continuation of #208 / #1188.
Note that `Py_Finalize()` is still commented out, because of a different segfault encountered when exiting the ipython->rpy2->reticulate stack that I didn't fully track down.
This patch fixes the segfault encountered on the default code path when a user launched an interactive session with ipython, initialized reticulate through rpy2, and then exited normally.
> don't replace `input()` builtin if R is embedded in Python

- R/conda.R
- man/conda-tools.Rd
Documentation for the `packages` argument shows indications to set the Python version instead of a package version.
> Fix documentation error for the `packages` argument

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- src/libpython.cpp
- src/python.cpp
- Restores compatibility with python2, after it was removed without ceremony in the last release
- Issue a warning when binding to python2 that this is the last reticulate release with python2 compatibility.
closes: #1241, #1229
> Restore Python 2 compatibility; deprecate Python 2 compatability

- NEWS.md
- R/conda.R
- R/pyenv.R
@kevinushey I'm admittedly not a very heavy user of brew. Do you see any pitfalls with this approach? 
(pyenv goes specifically looking for brew untapped build deps, and if this fails for any reason, then everything should still work, albeit slower since openssl@1.1 needs to be built from source.)
> use brew to install some python build deps if brew is available

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- R/knitr-engine.R
- tests/testthat/resources/eng-reticulate-example.Rmd
This addresses an [issue with quarto users](https://github.com/quarto-dev/quarto-cli/issues/1501) who expect the behavior of Python cells to more closely match those of quarto's Jupyter engine.
I'm happy to add supporting tests/documentation, though I could use some help navigating your expectations on that!
(@kevinushey thanks for the help!)
> add support for _repr_markdown_ IPython methods

- NEWS.md
- R/conda.R
- R/miniconda.R
closes #1286
Ensure additional conda directories are on 
the PATH when invoking the conda binary.
> fix conda/ssl/installation error

- R/testthat-helpers.R
- inst/python/rpytools/loader.py
- tests/testthat/resources/import-test.R
- tests/testthat/test-python-import-hook.R
Fixes an issue where module names (especially in recursive imports) might not be properly resolved.
> resolve module names in import hook

- R/conda.R
The `conda_remove()` implementation interprets a `packages=NULL` argument as `--all`, removing the environment. This PR documents this important behavior.
https://github.com/rstudio/reticulate/blob/a1d7f7f573f652212bc2c72c39317340e6d8b511/R/conda.R#L362-L363
> document environment removal

- inst/config/config.py
sys.path[0] is often an empty string, but that isn't always the case. This fixes a problem I had using a non-standard python interpreter ([spack python](https://spack.readthedocs.io/en/latest/developer_guide.html#cmd-spack-python))
> More explicitly remove problematic PYTHONPATH entries

- R/miniconda.R
At the moment, when `RETICULATE_MINICONDA_ENVNAME=base` reticulate tries to load `<conda path>/envs/base` and as it does not exists it tries to create it which leads to:
```
+ '/opt/conda/bin/conda' 'create' '--yes' '--prefix' '/opt/conda/envs/base' 'python=3.8' 'numpy' '--quiet' '-c' 'conda-forge'
CondaValueError: 'base' is a reserved environment name
Error: Error creating conda environment '/opt/conda/envs/base' [exit code 1]
```
This is a proposal to fix that case.
> fix RETICULATE_MINICONDA_ENVNAME=base

- NEWS.md
- R/utils.R
- inst/python/rpytools/call.py
- src/python.cpp
Rcpp release 1.0.10 turned on use of `R_UnwindProtect()` by default. Previous versions of Rcpp would eval R code with a `tryCatch()`, silently catching errors instead of propagating them back up to the user session. Reticulate was implicitly depending on this behavior in various locations.
With this patch, reticulate explicitly places a `tryCatch()` on the stack when Python is calling back into R, and then reticulate will raise a python Exception if an R error was caught.
closes https://github.com/rstudio/reticulate/issues/1328
> invoke R functions from Python with `tryCatch()`

- NEWS.md
- src/libpython.h
Also add `Py*_CheckExact()` macros,  with the previous implementation.
This change makes the type check macros match
the behavior of the same named macros in the Python API.
closes: #1226
related: #1352, #1348
> update `Py*_Check()` macros to accept subtypes

- NEWS.md
- R/RcppExports.R
- R/python.R
- src/RcppExports.cpp
- src/libpython.cpp
- src/libpython.h
- src/python.cpp
- tests/testthat/test-python-formals.R
To check that this doesn't have a major impact on conversion times, I did some quick benchmarks by timing how long it takes to convert all callables in the tensorflow module, going down 3 levels of recursion (~22k callables)
```r
Sys.setenv("CUDA_VISIBLE_DEVICES" = "")
library(tensorflow)
py_is_callable <- import_builtins()$callable
stack <- fastmap::faststack(22500)
fetch_functions <- function(x, depth = 0, path = character()) {
nms <- py_list_attributes(x)
nms <- nms[!startsWith(nms, "_")]
for(nm in nms) {
if (depth > 3) return()
obj <- x[[nm]]
if (py_is_callable(obj)) {
obj_ <- list(obj)
names(obj_) <- paste0(c(path, nm), collapse = ".")
stack$push(obj_)
}
if (inherits(obj, c("python.builtin.module", "python.builtin.type"))) {
fetch_functions(obj, depth = depth + 1, …
```
> R wrapper functions with matching Py callable signature

- .github/workflows/R-CMD-check.yaml
- src/libpython.cpp
- src/libpython.h
- src/python.cpp
- tests/testthat/test-python-objects.R
Fixes two issues with TensorFlow, where `dict`s and `list`s assigned as an attribute of a Keras model failed to convert back to an R `list()` when accessed from R. The cause of the issue is that any container assigned to a model get transformed into a more complex object that no longer works with the standard Python C API code for lists and dicts.
This PR is also a slight reversion of #1354, which relaxed the check for lists to from `PyList_CheckExact()` to `PyList_Check()` before passing the object to the `PyList_*` C functions. This goes back to using `PyList_CheckExact()` to make sure an object is safe to pass to `PyList_*` (and similar for `dict`s).
> fix conversion of subclassed dict() and list()

- R/config.R
- R/python.R
- R/utils.R
- inst/config/config.py
- src/python.cpp
- tests/testthat/test-python-exceptions.R
As a stack with multiple r->py->r->py frames is unwinding due to an exception propagating, the python runtime can move or discard the attrs attached to the exception object. This PR addresses two scenarios where the original `r_trace` attr is no longer attached to the exception we get back from Python. 
1.  A new python exception is raised while the previous error is still propagating. Here, the original exception is still available under `__context__`.
2.  A new python exception is raised after the previous error is caught and cleared.
Without this PR, a truncated r_trace containing only a fraction of the full stack would be attached to the exception. Both these scenarios were encountered in keras/tensorflow.
Also, included is a minor fix for identifying conda python from …
> Fixes to avoid attaching a truncated `r_trace` to exceptions

- R/python-tools.R
The regex `script <- sub("^#\\s+cmd: (.+)\\s+create\\s+.*", "\\1",  lines[[1]])` failed to get the right path.
I create this env with "rename": `# cmd: /home/gaoch/anaconda3/bin/conda rename --name tensorflow2 tensorflow`. So, in my computer, there is no `conda create` history; and maybe the `lines[[1]]` is not `conda create` command in some other situations.
Therefore, I suggest to edit this regex to fix this issue.
This works for me, and should be also useful for similar errors.
> Fix of Error in normalizePath(conda, winslash = "/", mustWork = TRUE)

- R/conda.R
- R/use_python.R
@t-kalinowski 
This is a proposed solution for handling micromamba called by using `use_condaenv("~/path_to_env", "~/pathto_micromamba/micromamba")` followed by `source_python('mypython.py')`. Addresses #1378 and #1176 I introduced a global and addressed errors during initialization. Tried to minimize behavior changes. I don't have a windows machine to test this more extensively on. There might still be changes needed for conda_run2_windows().
Best,
Zia
> address use of micromamba during initialization see #1378 and #1176

- NEWS.md
- R/knitr-engine.R
This is a first attempt to replicate the default Jupyter behavior with
Reticulate.
That is:
* Always display plots
* Do not display results of code expressions unless at last code line.
* Display result of final expression unless suppressed with ;
See: gh-1391
> MRG: First draft of jupyter_compat mode

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- R/generator.R
- inst/python/rpytools/generator.py
- man/py_iterator.Rd
`py_iterator()` is used to create a python iterator from an R function. This PR adds a `prefetch` argument to `py_iterator()`. 
TensorFlow/Keras can accept user defined iterators for producing data (e.g., batches of training data). TensorFlow will in some circumstances call `iterator.__next__()` from a Python background thread which has the GIL acquired, and with the main thread fully blocked in a C++ call until the `__next__()` call has completed. 
With an iterator which calls an R function, this results in either:
- A `stackOverflowError` R error (or segfault, or corrupted data), due to the R API being called from the non-main thread. 
- A deadlock, where the main thread is blocked waiting on the R function to run, and the R function call is waiting to run on the main thread.
One such …
> Add `prefetch` arg to `py_iterator()`

- NEWS.md
- src/python.cpp
- tests/testthat/test-python-objects.R
While working on the latest threading issues in TF 2.13 (#1405), I observed that `py_capsule()` finalizer may access the R API from not the main thread, if the last `Py_DecRef()` on the object is called from a background thread. This PR fixes that, ensuring that the finalizer only accesses the R API from the main thread.
> Ensure `py_capsule` finalizer runs on main thread

- src/event_loop.cpp
- src/libpython.cpp
- src/libpython.h
- src/python.cpp
Presently, long running Python calls in `repl_python()` that stream to stdout will not show any output in the R console until the Python call has fully returned. This PR add periodic calls to flush the stdout and stderr buffers from the event loop, ensuring that streaming python output is visible in the R console.
Related: https://github.com/rstudio/reticulate/issues/739
cc: @falbukrek
> flush python stdout/stderr from event loop.

- src/python.cpp
This fixes #1404 in the sense that we no longer segfault when calling `import_builtins()$globals()`. 
The segfault happens because the call to `globals()` fails but never sets an exceptionType in Python side, which is expected by the `py_fetch_error()`.
The reason why this call fails is still unkown to me (no backtrace makes it harder to figure it out), but it it seems that, the Python interpreter used by reticulate has no default module imported, causing the globals dictionary to not exist.
I think we might be missing somehting like:
https://github.com/rstudio/reticulate/blob/9a712cbb453595621ba157b308682c5844b5944b/src/python.cpp#L2967-L2968
during the initialization of reticulate's interpreter.
Previous reticulate versions raise:
```
> reticulate::import_builtins()$globals()
Error: …
```
> Avoid segfault when raising Python errors that didn't set an exception.

- R/output.R
- inst/python/rpytools/output.py
- tests/testthat/_snaps/python-knitr-engine/knitr-print2.md
- tests/testthat/test-python-knitr-engine.R
Follow up for https://github.com/rstudio/reticulate/pull/1412#issuecomment-1644001337
> Fix knitr output remapping from a clean new session

- src/python.cpp
- tests/testthat/test-python-numpy.R
Fixes #1409, also refer to linked issue for more details on the approach.
> Correctly handles Fortran ordering in numpy character arrays

- R/knitr-engine.R
- tests/testthat/resources/eng-reticulate-example.Rmd
- tests/testthat/test-python-knitr-engine.R
Should make testthat output less verbose.
> Render markdown quietly to avoid flooding tests

- NEWS.md
- R/config.R
- R/import.R
- R/install-python.R
- R/install.R
- R/package.R
- R/pyenv.R
- R/use_python.R
- R/utils.R
- R/virtualenv.R
- README.md
- man/import.Rd
- man/py_discover_config.Rd
- man/virtualenv-tools.Rd
- vignettes/package.Rmd
- vignettes/python_dependencies.Rmd
- vignettes/python_packages.Rmd
- vignettes/versions.Rmd
This PR adjusts the logic that reticulate uses to determine which python installation to load. The changes are mostly related to the choices reticulate makes in the absence of any concrete preference expressed by the user via `use_python()`, `RETICULATE_PYTHON`, or similar.
Previously, reticulate would prompt the user to install miniconda, bootstrap a "r-reticulate" conda environment, or go searching through all known venvs and conda envs for the presence of a requested module.
New behavior highlights:
-   No longer prompt to install miniconda. Instead, at a similar point in the order of discovery, we prompt the user to instead create a default "r-reticulate" venv.
-   We give higher precedence now to explicitly provided hints of the form:
-   `import("bar", delay_load = list(environment …
> Changes to how we pick which Python to use.

- R/knitr-engine.R
- tests/testthat/_snaps/python-knitr-engine/knitr-print.md
- tests/testthat/_snaps/python-knitr-engine/knitr-print2.md
- tests/testthat/resources/knitr-print.Rmd
Should fix: https://github.com/rstudio/reticulate/issues/1387#issuecomment-1645724902
@matthew-brett Can you confirm this is the expected behavior?
> Still include the stdout output captured before the autoprint mechanism.

- R/config.R
- R/import.R
- R/package.R
- R/pyenv.R
- R/python.R
- R/virtualenv.R
- R/wrapper.R
- tests/testthat/test-delay-load.R
- tests/testthat/test-python-dict.R
- tests/testthat/test-python-exceptions.R
- vignettes/python_dependencies.Rmd
This PR enables reticulate to register (and respect) python environments preferences from multiple calls to `import(delay_load = list(environment = <nenvame>))`.
For example
```r
library(tensorflow)
library(keras)
```
Would previously cause reticulate to forget the request for the `r-tensorflow` environment, due to the `r-keras` request having higher precedence. Now, all requested python environment names are remembered and searched for, in order of `priority`.
> allow registering multiple delay_load requests

- R/python-item.R
- R/python.R
- src/python.cpp
- use C++ scope guard for PyErr restoration
- speed up case when `silent = TRUE`
- avoid invoking python getattr/getitem method twice due to use of R py_has_*()
- avoid overhead of R condition handlers
- use emptyenv() as sentinel instead of py_none()
> refactor `py_get_attr()` / `py_get_item()`

- R/knitr-engine.R
- man/eng_python.Rd
I think this covers all knitr options that the Python engine deals explicitly. There might be other options that are just used by knitr.
> Add documentation for most most Python engine options.

- NEWS.md
- src/libpython.h
- src/python.cpp
- tests/testthat/test-python-pandas.R
- vignettes/calling_python.Rmd
Related #197 and #207
This PR adds an optional behavior for handling of R data.frame atomic columns when converting into pandas data.frames. The main motivation for this PR is to better handle R data frames that contain columns with `NA`s.
If the `reticulate.pandas_use_nullable_dtypes` is set, instead of converting into raw numpy data types, we use (newish) pandas [nullable data types](https://pandas.pydata.org/docs/user_guide/integer_na.html), that have built-in support for NA`s .
With the new behavior, doing:
```
df <- data.frame(
int = c(NA, 1:4),
num = c(NA, rnorm(4)),
lgl = c(NA, rep(c(TRUE, FALSE), 2)),
string = c(NA, letters[1:4])
)
options(reticulate.pandas_use_nullable_dtypes = TRUE)
r_to_py(df)
```
Results in:
```
int       num    lgl string
0  <NA>      <NA>   <NA>   <NA>
1 …
```
> Preserve NAs when casting R data.frames to pandas.

- R/virtualenv.R
> On Ubuntu, don't discover unusable system venv module.

- R/config.R
- R/package.R
- inst/config/config.py
Minor change to initialization routine, while working on #1461.
When patching `sys.executable`, we now fetch the actual value when probing config, instead of relying on the (potentially transformed) the path
used from reticulates init codepath.
Motivated by: on Windows, observed inconsistent usage of `/` and `\` as the path sep between "real" and "reticulate-set" values for this.
Also, I see no reason to confine this to windows only: `sys.executable` should be set properly on all platforms.
> patch `sys.executable` not just on windows

- NEWS.md
- inst/python/rpytools/subprocess.py
- tests/testthat/test-subprocess.R
asyncio.windows_utils subclasses/aliases `subprocess.Popen` like this:
```python
class Popen(subprocess.Popen)
def __init__(...):
...
try:
super().__init__(...)
...
```
Calling `partial()` on `Popen` directly works when
using it like a function, but breaks when
subclassing Popen (like asyncio does).
This means that any modules that attempt to import asyncio will
fail as well, like tensorflow.
Closes https://github.com/rstudio/keras/issues/1375 Closes #1478
> fix `import asyncio` on Windows in RStudio

- DESCRIPTION
- inst/python/rpytools/subprocess.py
... instead of using `fuctools.partialmethod()`
Modules like asyncio that wrap Popen will pass `stdin=None`, bypassing the partial'ed default.
Closes #1484
> hand-roll wrapper for `Popen.__init__`

- inst/config/config.py
Previous logic breaks when Python 3.10+ is used. Replace with proper version check, as per [documentation](https://docs.python.org/3/library/sys.html#sys.version)
> avoid sys.version in config.py

- NEWS.md
- R/virtualenv.R
Update regex for `dpkg -l` output.
closes #1495
> Fix `python3-venv` detection on Ubuntu 22.04

- R/RcppExports.R
- R/python.R
- src/RcppExports.cpp
- src/python.cpp
Encountered in Keras 3, `keras.KerasTensor()` has a `__bool__()` method that raises an exception. 
The IDE calls `length()` when populating the environment pane. If a `KerasTensor` is defined in the R environment, this would reset the exception cached and presented by `py_last_error()`. This ensures that calling `length()` (as the IDE does) does not reset the user facing python exception.
> guard against exception-raising `__bool__` in `length()`

- NEWS.md
- src/python.cpp
- tests/testthat/test-r-extptr-capsule.R
R external pointers were wrapped as a python Capsule (in `r_extptr_capsule(...)`) but never properly unwrapped by `py_to_r`. As the `r_extptr_capsule(...)` function stores the pointer address in the Capsule, and the corresponding R object in the Capsule's "context" field, the original R external pointer can be easily retrieved. This preserves the external pointer's finaliser.
Example of usage:
```R
library(Rcpp)
Rcpp::sourceCpp(code='
#include <Rcpp.h>
using namespace Rcpp;
class AClass {
public:
AClass() {
printf("AClass created\\n");
}
~AClass() {
printf("AClass destroyed\\n");
}
};
// [[Rcpp::export]]
SEXP getA() {
AClass* ptr = new AClass;
return Rcpp::XPtr< AClass >(ptr);
}
')
x = getA() #<--- AClass created
xpy = r_to_py(x)
x_ = py_to_r(xpy)
identical(x,x_) #<--- …
```
> Unwrapping extptr stored in capsules

- NEWS.md
- R/conversion.R
- tests/testthat/test-python-scipy-sparse-matrix.R
This PR solves an issue with converting csc matrices with unsorted indices, similar to #727.
* Add test to check whether reticulate can convert csc_matrix, csr_matrix and coo_matrix with unsorted indices
* Sort indices of csc_matrix before converting to dgCMatrix
In https://github.com/rcannood/reticulate/pull/1, the CI checks fails for the first commit (in which I added a test to detect this problem), but the CI checks succeed for the second commit (in which I added the fix).
> Fix issue with unsorted indices in csc_matrix

- NEWS.md
- R/knitr-engine.R
The [knitr documentation](https://yihui.org/knitr/options/#plots) indicates that it is possible to pass a vector of target devices to save the same plot in different formats. Reticulate uses `dir.create()` to create the destination directory if it doesn't exist, however this function can only accept one path and will fail with multiple target devices, as `knitr::fig_path()` will return a vector of 2 paths.
This PR solves the issue by considering the return type of `knitr::fig_path()` as a vector of strings rather than a single string and calling `lapply` on functions that relies on a single element.
> Save plot images in different formats with `opts_chunks$dev`

- NEWS.md
- R/knitr-engine.R
- tests/testthat/resources/test-custom-root-dir.Rmd
- tests/testthat/test-python-knitr-engine.R
> knitr: save and process figures from the correct wd

- NEWS.md
- src/python.cpp
- tests/testthat/test-python-objects.R
This PR:
- disables auto-conversion of subclassed Python dict and list types to R objects.
- Changes how the S3 `class` attribute is constructed for Python objects, from using `object.__class__` to using `type(object)`. In almost all scenarios, this should be a no-change, unless there is Python "magic", where the `__class__` attribute is explicitly modified after the Python object is constructed. Specifically, this is motivated by TensorFlow's usage of [`wrapt.ObjectProxy`](https://wrapt.readthedocs.io/en/latest/wrappers.html)
If the old behavior is desired, you can define an S3 method which casts the subclassed object type in Python using the built-in `list` or `dict` function. E.g.,:
```r
py_to_r.my_py_subclassed_list <- function(x) {
reticulate::import_builtins()$list(x)
}
```
Closes: …
> disable auto conversion of subclassed dicts and lists

- NEWS.md
- R/knitr-engine.R
- tests/testthat/resources/altair-example.Rmd
> Add support for multiple Altair compound charts

- NEWS.md
- R/conversion.R
- tests/testthat/test-python-pandas.R
Pandas 2.2 emits a warning when using the `Index.format()` method, which is used by reticulate py_to_r conversion routines. This PR updates usage from `index.format()` to `list(index.astype(str))` 
```
sys:1: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
```
closes #1537
> fix pandas v2.2 FutureWarning

- NEWS.md
- R/python-tools.R
Looks like the previous regex only supported environments created with the `conda create` or `conda rename` commands, this adds support for `conda env create`.
> fix regex to support environments created with conda env create

- R/conda.R
- man/conda-tools.Rd
This patch allows reticulate to bind to a condaenv where the original conda binary that was used to create the condaenv is no longer available. In that case, reticulate will fall back to the same search path as `conda_binary("auto")`. 
Note, we still require that a conda binary is available on the system to use a condaenv. Reticulate uses this to call the `conda activate` command. 
The relevant "Finding Conda" section in `?conda_binary` is reproduced here: 
> When conda = "auto", reticulate will attempt to automatically find a conda installation. The following locations are searched, in order:
> 
> 1. The location specified by the `reticulate.conda_binary` \R option,
> 2. The location specified by the `RETICULATE_CONDA` environment variable,
> 3. The [miniconda_path()] location (if it …
> `use_condaenv()` fixes

- NEWS.md
- R/config.R
This fixes an issue where a user could be prompted to create the default "r-reticulate" venv multiple times. For example:
```r
reticulate::py_eval("")
Would you like to create a default python environment for the reticulate package? (Yes/no/cancel) y
Would you like to create a default python environment for the reticulate package? (Yes/no/cancel) y
Would you like to create a default python environment for the reticulate package? (Yes/no/cancel) y
...
```
> Fix duplicate prompts to create a default venv.

- NEWS.md
- R/knitr-engine.R
Addresses https://github.com/rstudio/rstudio/issues/13840.
@cderv does this look like the right fix to you?
> prefer 'agg' for non-interactive R

- R/import.R
This is an internal change allowing usage like this in tensorflow, where `length(environment) > 1`:
```r
tf <- NULL
.onLoad <- function(libname, pkgname) {
...
tf <<- import("tensorflow", delay_load = list(
priority = 5, # keras sets priority = 10
environment = c("r-tensorflow", "r-keras"),
...
```
No doc changes because this mechanism for expressing soft import preferences is overly complex because of legacy support for both conda and virtual envs, (and the `priority` mechanism is not exposed intentionally). 
Most package authors looking to accomplish something similar would be better served by multiple calls to `use_python(,required = FALSE)`, e.g.
```r
tf <- NULL
.onLoad <- function(libname, pkgname) {
...
use_virtualenv("r-tensorflow", required = FALSE)
use_virtualenv("r-keras", …
```
> allow delay_load list to list multiple environments

- src/python.cpp
This is a workaround for an issue encountered on Windows, where calling `py_get_attr(silent = TRUE)` raised an exception. 
https://github.com/rstudio/tensorflow/actions/runs/8439823909/job/23115333998?pr=594
```
── Error ('test-as_tensor.R:6:5'): as_tensor works ─────────────────────────────
<python.builtin.SystemError/python.builtin.Exception/python.builtin.BaseException/python.builtin.object/error/condition>
Error in `py_get_attr_impl(x, name, TRUE)`: SystemError: _PyEval_EvalFrameDefault returned a result with an error set
Run `reticulate::py_last_error()` for details.
Backtrace:
▆
1. ├─tensorflow (local) test_is_tensor(as_tensor(3, tf$int64), tf$int64) at test-as_tensor.R:32:3
2. │ ├─testthat::expect(...) at test-as_tensor.R:6:5
3. │ └─"tensorflow.tensor" %in% class(x)
4. …
```
> Call `PyErr_Clear()` instead of `PyErr_Restore()` in `py_get_attr_impl(silent = TRUE)`

- NEWS.md
- R/package.R
- src/python.cpp
Packages may want to place multiple `use_python()` calls in `.onLoad()`, e.g., tensorflow might do:
```r
.onLoad <- function(...)
use_virtualenv("r-tensorflow", required = FALSE)
use_virtualenv("r-keras", required = FALSE)
}
```
This patch removes the warning issued by reticulate if a soft Python environment preference like was ignored.
> Remove warning about unused `use_python(,required=FALSE)` calls

- NEWS.md
- R/python.R
- inst/python/rpytools/output.py
- tests/testthat/test-python-output.R
This adds support for nested `py_capture_output()` calls. I.e., 
```r
py_capture_output({
py_capture_output({
py_run_string("print('hello')")
})
})
```
See the included tests for a fuller example.
The issue with the previous implementation was discovered while investigating a segfault in the Keras testsuite, which would in some situations setup multiple `py_capture_output()` contexts. When that happened, the reference to the original `sys.stdout` would be lost permanently, resulting in no further output, and a cryptic R error message each time `flush_std_buffers()` was invoked from C++ functions or from the R top-level task callback.
> Add support for nested `py_capture_output()` calls.

- R/python.R
- inst/python/rpytools/output.py
Small followup to #1564, making it safe to call `ctxt.collect_output()` before `ctxt.__exit__()` (enabling usage in ``on.exit(ctxt$`__exit__`())``
Also, a variable rename, for clarity.
> Update capture output streams

- .Rbuildignore
- .gitignore
- NEWS.md
- src/libpython.cpp
- src/python.cpp
> rchk fixes

- R/conversion.R
- src/python.cpp
- tests/testthat/test-python-pandas.R
> Fix pandas conversion if external packages define `py_to_r()` S3 methods for pandas subobjects. 

- vignettes/python_dependencies.Rmd
- Fix `DESCRIPTION` field name, i.e. remove the `/autoconfigure` from `Config/reticulate/autoconfigure` as the code doesn't know that suffix, cf. https://github.com/rstudio/reticulate/blob/5774c590c8658da133f53dcc1b2474e276b49748/R/python-packages.R#L231
- Improve language and formatting and fix typos.
Note that another round of editing wouldn't hurt (but I don't have the motivation for this right now):
- The text is still very redundant, i.e. it repeats itself unnecessarily often.
- I think the information about default usage of Miniconda is not accurate anymore.
> Improve `python_dependencies` vignette

- NEWS.md
- R/conda.R
- man/conda-tools.Rd
Fixes #1583 with additional optional arguments. The same general approach could possibly could be extended to all `conda` calls (e.g., `conda clone`, `conda export`), but I've kept the scope limited to `create` and `install` for now.
> Allow users to pass extra command-line arguments for conda create, install.

- NEWS.md
- R/conda.R
As discussed in #1585, this ensures that Python installation inside `conda_install()` respects the user-defined channels.
> Respect user-specified channels when installing Python in conda_install().

- NEWS.md
- R/virtualenv.R
Fixes a warning observed in https://github.com/rstudio/tensorflow/issues/597
This silences a warning if, for example, `/usr/local/bin/python3` is a broken symlink on the user's system.
> Ignore broken links encountered by `virtualenv_starter()`

- R/package.R
- R/python.R
- inst/python/rpytools/call.py
- src/event_loop.cpp
- src/libpython.cpp
- src/libpython.h
- src/python.cpp
- src/signals.cpp
This is a followup to #1602, split off to keep #1602 small and readable. This PR includes some refactoring of `py_to_r(<python.builtin.Exception>)` conversion, and `call_r_function()` exception handling.
> Refactor interrupt and exception handling

- NEWS.md
- R/python.R
closes #1604
Example output:
```r
> py_eval("print")
<builtin_function_or_method builtins.print(*args, sep=' ', end='\n', file=None, flush=False)>
> py_eval("RuntimeError")
<type builtins.RuntimeError(*args, **kwargs)>
> keras <- import("keras")
> keras$layers$Dense
<type keras.src.layers.core.dense.Dense(
units, 
activation=None, 
use_bias=True, 
kernel_initializer='glorot_uniform', 
bias_initializer='zeros', 
kernel_regularizer=None, 
bias_regularizer=None, 
activity_regularizer=None, 
kernel_constraint=None, 
bias_constraint=None, 
lora_rank=None, 
**kwargs
)>
```
> Print Python callables with their signature

- NEWS.md
- R/python.R
This is a followup to #1605, updates the printed output. We no longer discard the default `x.__repr__()` output, and we present typed instances a little more intuitively. 
New example output:
```r
> keras <- reticulate::import("keras")
> builtins <- reticulate::import("builtins")
> keras$losses$BinaryCrossentropy
<class 'keras.src.losses.losses.BinaryCrossentropy'>
signature: (
from_logits=False, 
label_smoothing=0.0, 
axis=-1, 
reduction='sum_over_batch_size', 
name='binary_crossentropy'
)
> keras$losses$BinaryCrossentropy()
<keras.src.losses.losses.BinaryCrossentropy object at 0x710d39fe5e90>
signature: (y_true, y_pred, sample_weight=None)
> builtins$print
<built-in function print>
signature: (*args, sep=' ', end='\n', file=None, flush=False)
> builtins$repr
<built-in function repr> …
```
> Update print method for Python callables

- NEWS.md
- R/conda.R
Allow using a `mamba` binary instead of `conda`.
Currently, the `mamba` binary gets overriden with `conda`, even if using the version of `mamba` in the `bin` directory. We preserve the behavior of overriding `condabin` with `bin` if an executable exists in that folder
> Support non-conda binaries

- NEWS.md
- src/tinythread.h
Attempting to install `reticulate` on Windows ARM64 fails with the error:
```
* installing *source* package 'reticulate' ...
** using staged installation
** libs
using C++ compiler: 'clang version 17.0.6'
clang++ -std=gnu++17  -I"C:/PROGRA~1/R-AARC~1/R-devel/include" -DNDEBUG  -I'C:/Users/andrew/AppData/Local/R/aarch64-library/4.5/Rcpp/include' -w  -I"C:/rtools44-aarch64/aarch64-w64-mingw32.static.posix/include"     -O2 -Wall    -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++17  -I"C:/PROGRA~1/R-AARC~1/R-devel/include" -DNDEBUG  -I'C:/Users/andrew/AppData/Local/R/aarch64-library/4.5/Rcpp/include' -w  -I"C:/rtools44-aarch64/aarch64-w64-mingw32.static.posix/include"     -O2 -Wall    -c event_loop.cpp -o event_loop.o
event_loop.cpp:40:10: error: unknown type name 'sig_atomic_t'
40 | …
```
> Include signals.h on Windows ARM64

- NEWS.md
- src/python.cpp
This PR fixes the current NOTE on R devel CRAN machines about usage of non-API C entry points.
```
Version: 1.37.0
Check: compiled code
Result: NOTE 
File ‘reticulate/libs/reticulate.so’:
Found non-API calls to R: ‘SET_BODY’, ‘SET_CLOENV’, ‘SET_FORMALS’
Compiled code should not call non-API entry points in R.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
Flavors: [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/reticulate-00check.html), [r-devel-linux-x86_64-fedora-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/reticulate-00check.html), [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/reticulate-00check.html)
``` …
> Moving into R's C API compliance

- NEWS.md
- tests/testthat/test-python-source.R
- vignettes/arrays.Rmd
- vignettes/calling_python.Rmd
- vignettes/package.Rmd
- vignettes/python_packages.Rmd
- vignettes/python_primer.Rmd
- vignettes/r_markdown.Rmd
- vignettes/rstudio_ide.Rmd
- vignettes/versions.Rmd
Recently, CRAN checks for reticulate started failing on macOS-oldrel.
After some investigation, it appears that the macOS-oldrel runners—and only the macOS-oldrel runners—set the environment variable `_R_CHECK_VIGNETTES_SKIP_RUN_MAYBE_=false` when running checks.
My understanding is that this results in the vignettes being processed with `knitr::purl()`, which converts them into a script. The script is then evaluated as part of the checks. In the context where the script is evaluated, `knitr` calls like `knitr::opts_chunk$set(eval = FALSE)` do not function, and chunks that are not meant to be evaluated in vignettes still get evaluated, leading to errors, and CRAN check failures.
This is affecting downstream packages and is also the reason why CRAN machines have not built a binary for the …
> Fixes for failing CRAN checks

- NEWS.md
- R/array.R
- update `array_reshape()` for NumPy 2.1
> Updates for NumPy 2.1

- NEWS.md
- R/config.R
- R/package.R
- R/repl.R
Fixes https://github.com/posit-dev/positron/issues/4457
> Patch `subprocess.Popen` when running on Windows under Positron

- vignettes/package.Rmd
Package authors should implement the `print()`, `format()`, `summary()`, and/or `str()` methods in R directly for Python objects.
> Remove recommendation to implement `py_str()` methods.

- NEWS.md
- R/package.R
- src/python.cpp
> Fix finalizer segfault

- NEWS.md
- src/RcppExports.cpp
- src/readline.cpp
I encountered a segmentation fault from reticulate's internal `readline()` function while evaluating interleaved R and Python chunks in RStudio within a Quarto document.
<details>
<summary>gdb backtrace</summary>
```c++
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:394
#1  0x00005adcfdb76186 in  ()
#2  0x00005adcfdb8006b in  ()
#3  0x00005adcfe1c229d in  ()
#4  0x00005adcfe1c2599 in  ()
#5  0x00005adcfe1c5218 in  ()
#6  0x00005adcfe1f36dc in  ()
#7  0x00005adcfe1f4f79 in  ()
#8  0x00005adcfdb49749 in  ()
#9  0x00005adcfdb311b2 in  ()
#10 0x00005adcfdb3427b in  ()
#11 0x00005adcfe6731f1 in  ()
#12 0x00007a0ecf92a29f in readline(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (prompt=">>> ") at …
```
> Fix segfault from `readline()`; avoid unnecessary string copy

- NEWS.md
- src/python.cpp
> Fix error when running under `radian`

- NEWS.md
- R/conda.R
- R/python-tools.R
Resolves https://github.com/rstudio/reticulate/issues/1654
`python_info_condaenv_find` was only being used by `get_python_conda_info` and `python_info_condaenv` so I combined it with `get_python_conda_info` and just repointed `python_info_condaenv` at `get_python_conda_info` so it also gets the fix.
> Handle invalid conda-meta/history value

- NEWS.md
- R/config.R
- R/virtualenv.R
Closes #1656
- Fixed an error where `py_discover_config()` attempted to check if a Windows App Store Python could be used.
- `py_discover_config()` will no longer automatically discover Windows App Store Python installations.
- `virtualenv_starter()` will also no longer discover Windows App Store Python installations.
> Fix error when encountering Windows App Store Python

- R/config.R
Closes: #1674
Fixes an issue where evaluating the Python expression 
```python
import sys; print(sys.platform)
```
via `system2()` did not raise an error, but the return value is not the expected scalar character vector.
> Better handle silent errors

- src/python.cpp
Currently, when activating a virtualenv, reticulate evaluates `activate_this.py` in `__main__`. With this PR, reticulate will now run the script using `runpy.run_file()`. This approach avoids polluting `__main__` with detritus and aligns more closely with the instructions in the `activate_this.py` script.
Related:
- https://github.com/astral-sh/uv/pull/7978
- https://github.com/pypa/virtualenv/blob/main/src/virtualenv/activation/python/activate_this.py
> Rewrite `py_activate_virtualenv()` to run `activate_this.py` isolated

- R/thread.R
- inst/python/rpytools/run.py
- tests/testthat/test-python-threads.R
Launching IPyKernel for the reticulate-backed Positron Python REPL currently clears Python's `__main__` namespace, including the `r` symbol injected for communication from Python to R. This pull request fixes that issue.
> Positron REPL: restore `__main__` members after ipykernel launch

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- R/RcppExports.R
- R/config.R
- R/package.R
- src/RcppExports.cpp
- src/libpython.cpp
- src/libpython.h
- src/python.cpp
- tests/testthat/test-python-class.R
- tests/testthat/test-python-objects.R
For Reticulate internals, [Python 3.13](https://docs.python.org/3/whatsnew/3.13.html) introduces two significant changes:
1. `PyObject_HasAttrString()` now emits a non-suppressible warning to stderr when it returns a false value:
```
Exception ignored in PyObject_HasAttrString();
consider using PyObject_HasAttrStringWithError(),
PyObject_GetOptionalAttrString(), or PyObject_GetAttrString()
```
To prevent this output from repeatedly appearing in users consoles, Reticulate internals have been refactored to use the new C entry points introduced in Python 3.13: `PyObject_HasAttrStringWithError` and `PyObject_GetOptionalAttrString`, with backports for older Python versions.
2. Quoting from [Python 3.13 release notes](https://docs.python.org/3/whatsnew/3.13.html)
> Support for chained …
> Updates for Python 3.13

- NEWS.md
- R/RcppExports.R
- src/RcppExports.cpp
- src/libpython.cpp
- src/python.cpp
This PR removes all remaining usages of `PyObject_HasAttrString()` from the codebase, to prevent warnings like this from being presented to users:
```
>>> from itertools import islice
Exception ignored in PyObject_HasAttrString(); consider using PyObject_HasAttrStringWithError(), PyObject_GetOptionalAttrString() or PyObject_GetAttrString():
Traceback (most recent call last):
File "/Users/tomasz/github/rstudio/reticulate/inst/python/rpytools/call.py", line 6, in python_function
return call_r_function(f, *args, **kwargs)
RuntimeError: <text>:1:2: unexpected input
1: __
^
```
> More updates for Python 3.13

- NEWS.md
- R/ark-variables-methods.R
- R/zzz.R
- inst/python/rpytools/ark_variables.py
This PR adds support for reticulate objects in the Positron Variables Pane. 
With an example session:
```r
Sys.unsetenv("VIRTUAL_ENV")
library(keras3)
anint <- py_eval("1", FALSE)
adict <- py_eval("{'a':1, 'b':2}", FALSE)
adict['foo'] <- adict # recursive
alist <- py_eval("['a', 1]", FALSE)
atuple <- py_eval("('a', 1)", FALSE)
input <- keras_input(c(24, 24))
output <- input |>
layer_dense(32, "relu") |>
layer_dense(10, "softmax")
model <- keras_model(input, output)
```
We now see:
https://github.com/user-attachments/assets/30e1d667-63ed-4435-a568-dc4bfff1b04e
Previously, all python objects presented as:
This uses the ark interface added in https://github.com/posit-dev/ark/pull/560 and https://github.com/posit-dev/ark/pull/561
> Add Positron Variables Pane Methods

- R/python.R
This is a partial followup to #1688
> restore `length(<delayed_module>)` not forcing the module.

- src/pending_py_calls_notifier.cpp
Noticed this as I was updating my local R-devel stack:
```sh
ccache g++-14 -I"/usr/local/lib/R-devel/lib/R/include" -DNDEBUG  -I'/usr/local/lib/R-devel/lib/R/library/Rcpp/include' -I/usr/local/include    -fpic  -O3 -Wall -pipe -pedantic -Wno-parentheses -Wno-nonnull -Wno-ignored-attributes  -flto  -DR_NO_REMAP -c signals.cpp -o signals.o
pending_py_calls_notifier.cpp:13:9: warning: "R_NO_REMAP" redefined
13 | #define R_NO_REMAP
|         ^~~~~~~~~~
<command-line>: note: this is the location of the previous definition
```
The two added lines should take care of it.  While only needed for R-devel now, this is (per R NEWS recently) becoming the C++ default.
> Redefine R_NO_REMAP only if not defined

- R/config.R
- R/package.R
- R/pip.R
- R/utils.R
- R/virtualenv.R
- reticulate.Rproj
Fixes #1712
Possibly fixes #1713 also.
> Prefix Python venv starter lib to `LD_LIBRARY_PATH`

- R/repl.R
- src/python.cpp
For consistency with the native Python repl.
> Accept `quit()` and `exit()` in `repl_python()`

- R/py_require.R
- tests/testthat/_snaps/py_require.md
- tests/testthat/test-py_require.R
- `uv run` does not accept Python version `==3.11`, and `==3.09`. In this change, `py_require()` removes any `==` from Python version requirements
- `uv run` does not accepts any combination of `==` requirements with non-equal requirements (`>=`, `<=`). In this change, `py_require()` checks and returns an informative error
- `uv run` does not accept more than one, different, equal-to Python version. In this change, `py_require()` will check and return an error this occurs 
- Adds tests for the changes mentioned above, and updates tests that were sending equal and non-equal Python requirements
- Unrelated, but just found out that newer pre-release versions of packages will modify the error output (https://pypi.org/project/tensorflow/#history), so switched the tests that requests a …
> `py_require()` checks and fails on 'equal' / 'not equal' Python version requests are used

- NEWS.md
- R/config.R
- R/install.R
- R/py_require.R
- tests/testthat/_snaps/py_require.md
- tests/testthat/helper-py-require.R
- tests/testthat/test-py_require.R
WIP. Current changes:
- Update order of discovery:
- continue to discover r-reticualte venv before bootstrapping
- only bootstrap a venv if initializing python
- give a way to opt out
- Update `uv_get_or_create_env()`:
- pass through stderr from uv
- simplify pre+post processing
- Update `uv_binary()`
- allow resolving without bootstraping install
- Update uv cache resolution:
- Fix issue where reticulate resolved the incorrect cache dir if a user-managed uv installation is used. Right now this is done by forcing to always use the reticulate cache, but it might make sense instead to let uv use it's default `uv cache dir` if the uv installation is not managed by reticulate.
- Changes to tests:
- declare requirements for tests with `py_require()` 
- capture stderr from uv in tests
- use …
> Updates to `py_require()`

- R/package.R
- R/py_require.R
- tests/testthat/_snaps/py_require.md
- Adds `reticulate_default_python()`
- `uv_get_or_create()` uses new function to get the default if no Python version is specified
- Updates `print.` and error `py_require()` output to clarify that it will use, or used, the default version
- Updates test snapshot
> Py require default python

- R/package.R
- R/py_require.R
- tests/testthat/_snaps/py_require.md
Currently, adding a Python constraint like `py_require(python_version = ">=3.8")` changes the selected Python from 3.11 to 3.13, which then results in errors when trying to install packages that are not compatible yet with the latest Python version (e.g., tensorflow, torch).
This PR implements a custom constraint resolver that prefers returning a bugfix Python release, rather than the bleeding edge. 
Some examples:
```r
> resolve_python_version()
[1] "3.11.11"
> resolve_python_version(">=3.9")
[1] "3.11.11"
> resolve_python_version(">=3.9")
[1] "3.11.11"
> resolve_python_version(">=3.11")
[1] "3.11.11"
> resolve_python_version(">=3.12")
[1] "3.12.8"
> resolve_python_version(">=3.13")
[1] "3.13.1"
> resolve_python_version("<=3.13")
[1] "3.11.11"
> resolve_python_version("<=3.11")
[1] …
```
> Implement `resolve_python_version()`

- DESCRIPTION
- R/py_require.R
- R/utils.R
- tests/testthat/test-py_require.R
`uv` recently started to default print informative messages about download operations on non-pty stdout, removing the need for a custom spinner in reticulate.
With this update, I now see:
> Simplify `uv_get_or_create_env()`; remove processx dependency

- R/config.R
- R/py_require.R
- R/utils.R
- R/virtualenv.R
- man/py_require.Rd
- man/py_version.Rd
- src/python.cpp
- tests/testthat/_snaps/py_require.md
- tests/testthat/helper-py-require.R
- tests/testthat/test-py_require.R
Changes in behavior:
- Don't signal error if called with an already satisfied requirement after Python has been initialized.
- Don't signal error if called with an unsatisfied requirement from a package after Python has been initialized.
-  Don't signal error if called with an unsatisfiable request before Python has been initialized. (Error is deferred until resolving the env, to give an opportunity in user code to proactively fix the requirements.)
-  In `uv_get_or_create_env()`, if python has been initialized, ensure we resolve the initialized python version.
- If an ephemeral uv env is initialized, only `action = "add"` for packages is supported.
- Add `...` to `py_require()` signature, require that `exclude_newer` and `action` are provided as named args. 
- Do not warn or show an …
> Updates to `py_require()`  

- R/py_require.R
- man/py_require.Rd
- tests/testthat/_snaps/py_require.md
This PR
- Allows rerunning scripts with (unchanged) `py_require(exclude_newer =)` calls
- Discusses `UV_OFFLINE` and `UV_PRERELEASE` envvars in the docs and error hints
- Adds a guardrail to error if user attempts to change a package version after it has already been loaded.
> Allow re-running scripts with `exclude_newer` set

- R/repl.R
Add support for passing input via `repl_python(input)` to the Positron REPL.
This is the mechanism used by the Quarto extension in Positron.
Companion PR: https://github.com/posit-dev/ark/pull/713
> Focus Python Console with`repl_python(input)` in Positron.

- R/py_require.R
- R/utils.R
- man/py_require.Rd
- vignettes/package.Rmd
I noticed that `uv self update` will fail if there are multiple self-updating-capable uv installations on a system.
Typically, if a `uv` is already installed, reticulate will use that. reticulate only bootstraps a uv installation into its cache dir if `uv` is not found.
However, before this PR, if user installs uv manually after reticulate has bootstraped an installation, then `self update` will later error with:
```
warning: Self-update is only available for uv binaries installed via the standalone installation scripts.
If you installed uv with pip, brew, or another package manager, update uv with `pip install --upgrade`, `brew upgrade`, or similar.
```
This is because the self-updater checks the `.config/uv/uv-receipt.json`, which is written to by install scripts unless self-updating is …
> Bootstrap unmanaged uv installation

- NEWS.md
- R/py_require.R
- man/py_require.Rd
This change prevents a reticulate-managed `uv` from writing to:
~/.cache/uv
~/.local/share/uv
> Refactor `uv` cache usage

- src/tinythread.h
Fix for issue reported via email:
> ```
> **********************************************************************
> From an attempt to add 'noreturn' in C++ as well as C:
> 
> In file included from pending_py_calls_notifier.cpp:14:
> In file included from /Users/ripley/R/R-devel/include/R.h:73:
> /Users/ripley/R/R-devel/include/R_ext/Error.h:65:3: error: 'noreturn' attribute
> does not appear on the first declaration
>   65 | [[noreturn]] void Rf_error(const char *, ...) R_PRINTF_FORMAT(1, 2);
>      |   ^
> ./tinythread.h:33:17: note: previous declaration is here
>   33 | extern "C" void Rf_error(const char* fmt, ...);
>      |                 ^
> 1 error generated.
> 
> Please use one or the other, preferably the R header.
> **************************************************************** …
```
> Accommodate changing definition of `Rf_error()`

- R/py_require.R
It truncates the package name if it's longer than the designated borders. It will shorten it enough to also prepend "..." to try to clarify that the name is shortened  
```r
> library(tensorflow)
> library(ragnar)
> reticulate::py_require()
══════════════════════════ Python requirements ══════════════════════════
── Current requirements ─────────────────────────────────────────────────
Python:   >=3.9, <3.13
Packages: numpy, tensorflow,
markitdown@git+https://github.com/microsoft/markitdown.gi...
── R package requests ───────────────────────────────────────────────────
R package  Python packages                           Python version      
reticulate numpy                                                         
tensorflow tensorflow                                >=3.9, <3.13 …
```
> Fixes to print method for py_require()

- NEWS.md
- R/py_require.R
- R/utils.R
- R/virtualenv.R
- man/py_require.Rd
- tests/testthat/_snaps/py_require.md
- tests/testthat/helper-py-require.R
- tests/testthat/test-py_require.R
> Support resolving system python versions by `py_require()`

- NEWS.md
- R/config.R
> Resolve `oldlibpath` even if nothing to set.

- NEWS.md
- src/python.cpp
- tests/testthat/test-python-base-r-generics.R
> Fix `[` with Python objects in `:` slice args

- R/thread.R
- R/zzz.R
This fixes the disappearing `r` object in the reticulate python console in Positron.
The problem is that with some folder renaming in Positron we were silently running the script without the workarounds to make `r` correcly appear in the console.
We should definitely update positron to call a dedicated entrypoint so we never silently fail when other file structure refactoring happens.
Opened https://github.com/posit-dev/positron/issues/6788 to track this issue.
> Make sure `py_run_on_thread` knows its initializing PositronIPyKernel

- R/install.R
This PR fixes a typo in the `py_install()` warning message suggested code: the set of packages is now all in one character vector passed as the first argument to `py_require()`.
> `py_install()`: fix warning message `py_require()` suggestion

- NEWS.md
- src/python.cpp
Fixes for the current CRAN Note:
```
Version: 1.41.0.1
Check: compiled code
Result: NOTE
File ‘reticulate/libs/reticulate.so’:
Found non-API calls to R: ‘OBJECT’, ‘Rf_GetOption’
Compiled code should not call non-API entry points in R.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual,
and section ‘Moving into C API compliance’ for issues with the use of
non-API entry points.
```
> R non-API updates

- NEWS.md
- R/conda.R
Fixes https://github.com/rstudio/rstudio/issues/15763#issuecomment-2740354896
This is untested as I don't have a proper r development environment to test, but the modification is very straightforward.
> Add direct check for micromamba and mamba executables, adjust preferred ordering

- NEWS.md
- R/conda.R
I was trying to use reticulate with a pixi env which only populates `conda-meta/history` with
```
// not relevant for pixi but for `conda run -p`
```
I have `options(reticulate.conda_binary = conda)` set to a copy of `micromamba.exe` to handle the conda related operations but when `use_python` tries to get the conda root/binary info it passes `NULL` to `normalizePath` if it can't find conda automatically, which causes the following error `Error in path.expand(path) : invalid 'path' argument` which is mentioned in https://github.com/rstudio/reticulate/issues/1184
```
1: source("src/r/conda.R")
2: withVisible(eval(ei, envir))
3: eval(ei, envir)
4: eval(ei, envir)
5: conda.R#9: use_python(pixi_env, required = TRUE)
6: python_config(python)
7: python_munge_path(python)
8: …
```
> Fix normalizePath null call with missing conda

- NEWS.md
- R/py_require.R
uv list can be slow on some systems. With this PR we use `only-managed` by default and only fallback to system python installations if no managed python is found which is required by some systems, see https://github.com/rstudio/reticulate/pull/1752/files
```
> system.time({uv_python_list()})
user  system elapsed 
0.016   0.022   0.089 
> system.time(uv_python_list(python_preference = "only-system"))
user  system elapsed 
0.994   1.340   5.977 
```
> Faster uv list

- NEWS.md
- R/py_require.R
- tests/testthat/_snaps/py_require.md
This PR switches `py_require()` to use `uv tool run` instead of `uv run`. This is so that internally uv resolves a `CachedEnvironment` instead of an `EphemeralEnvironment`.
Beginning with `uv` 0.8.0, `uv run --no-project` creates a truly ephemeral environment that is deleted at the end of the `uv` invocation. `uv tool run --isolated` invokes essentially the same code path within `uv`, except it returns the `CachedEnvironment` directly rather than layering a new `EphemeralEnvironment` atop it.
If upstream ever changes so that `uv tool run` also tears down the environment after the uv call finishes, we will probably have to materialize the environment within R's `tempdir()`. Note that would substantially complicate our current approach of displaying uv stderr output to the user. It would …
> Support uv version >=0.8

- NEWS.md
- R/python.R
- tests/testthat/test-python-with.R
- Forward the actual exception triple in `with.python.builtin.object` to the Python `__exit__` handler. This is so transactional context managers can roll back correctly.
- Add tests to ensure R errors and Python exceptions are passed along correctly.
Closes: #1840.
> Propagate exceptions to Python context managers in `with()`.
