rstudio/reticulate

vignettes/introduction.Rmd

Correct typo

---

inst/python/rpytools/help.py

Left a TODO for arg of type named list for future PR when someone gets a chance.

Support args of type list and tuple for doc generation

---

DESCRIPTION
NEWS.md
R/python.R

dict: don't scan parent frame for Python objects if a single unnamed list

---

R/config.R
R/use_python.R

Also removed `anaconda4` since it doesn't seem to exist yet.

Fix issue detecting miniconda

---

vignettes/versions.Rmd

And thanks for you hard work!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rstudio/reticulate/146)

just a small typo

---

R/package.R

This PR fixes a crash that seems to occur when attempting to interleave the loading of R packages with Python / Keras code. The code I was running to trigger the crash:
```R
library(keras)
imdb <- dataset_imdb()
c(x_train, y_train) %<-% list(imdb$train$x, imdb$train$y)
library(digest)
model <- keras_model_sequential()
model %>% 
layer_embedding(input_dim = 80, output_dim = 128) %>% 
layer_lstm(units = 64) %>% 
layer_dense(1, activation = "sigmoid")
```
When run from the R terminal, I saw:
```R
> model <- keras_model_sequential()
> model %>%
+   layer_embedding(input_dim = 80, output_dim = 128) %>%
+   layer_lstm(units = 64) %>%
+   layer_dense(1, activation = "sigmoid")
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```
The `mkl_intel_thread.dll` library is located within the …

candidate fix for crash seen w/new Anaconda

---

vignettes/versions.Rmd

I also made some minor grammatical changes

Clarified environment variable instructions

---

R/source.R
tests/testthat/script.py
tests/testthat/test-python-source.R

source_python() uses main module

---

R/help.R
R/wrapper.R

* Allows to register help handlers from Python functions documented in [Sphinx style](http://www.sphinx-doc.org/en/master/), which is popular in many Python packages. 
* Allows to generate wrappers for functions documented in Sphinx style. 
* Fixed issue with `py_function_wrapper` not handling enum items in param, e.g. `embedding_type` parameter in the example below.
Below is an example:
```
LFDA <- py_run_string("
class LFDA(object):
'''
Local Fisher Discriminant Analysis for Supervised Dimensionality Reduction
Sugiyama, ICML 2006
'''
def f1(self, num_dims=None, k=None, embedding_type='weighted'):
'''
Initialize LFDA.
Parameters
----------
num_dims : int, optional
Dimensionality of reduced space (defaults to dimension of X)
k : int, optional
Number of nearest neighbors used in local …
```

Support Sphinx style documentation help handlers and wrapper generation

---

src/python.cpp

Closes https://github.com/rstudio/reticulate/issues/185.

manage refcount in py_set_attr

---

R/help.R

capture output when parsing doctree

---

docs/articles/package.html
vignettes/package.Rmd

Fix typo in package vignette

---

src/python.cpp

Here are the minimal changes I needed to fix my use case. The enums had to be moved up because of ordering issues (could also add functions to header file). 
Here string checking also checks numpy scalar strings. Then it is also checked when converting to bytes.
As I said, I have not tested this against other issues - perhaps you have CI? I'm happy to respond to any comments you may have.

minimal changes to fix issue #248

---

inst/config/config.py

avoid use of 'imp' with Python 3

---

R/knitr-engine.R
tests/testthat/resources/eng-reticulate-example.Rmd

allow for syntax errors in Python chunks

---

R/output.R

cc: @randy3k; can you test this PR and let us know if it's sufficient for what you need?

allow configure of output stream remap

---

R/package.R
R/repl.R

ensure modules in pwd can be imported

---

NEWS.md
R/python.R

allow for functions called with 'r' helper

---

.travis.yml

To avoid issues like https://github.com/rstudio/reticulate/commit/70f1cf5d3b1f1e9f25e5b831034581f76d7ed7ea.

test older releases of R

---

R/use_python.R

Addresses #441
@kevinushey Could you do a code review?

use_python: verify required version when python is already initialized

---

NEWS.md
R/conversion.R
tests/testthat/test-python-datetime.R

fix buglet in date conversion

---

NEWS.md
R/conversion.R
tests/testthat/test-python-pandas.R

fix conversion of single-row data.frames

---

vignettes/python_packages.Rmd

just a typo during a copy paste from above 😉
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rstudio/reticulate/483)

this part is about virtualenv

---

R/RcppExports.R
R/conversion.R
src/RcppExports.cpp
src/python.cpp
tests/testthat/test-python-dict.R

Closes https://github.com/rstudio/reticulate/issues/516.
cc: @skeydan

properly handle conversion of ordered dictionaries

---

R/package.R
tests/testthat/helper-utils.R
tests/testthat/resources/venv-activate.R
tests/testthat/test-python-virtual-environments.R

This PR checks whether the user has requested a specific version of Python, and warns if the version of Python that was actually loaded differs from their requested version.
cc: @jjallaire

warn if request for specific Python not honored

---

R/conversion.R
src/python.cpp

Part of https://github.com/rstudio/reticulate/issues/551.

avoid use of iterate in conversion of dict

---

R/python-tools.R
R/virtualenv.R

As otherwise we can request a version of Python which lacks the requisite tools for initializing a virtual environment.

validate existence of required virtualenv modules

---

R/conda.R

Prefer conda.bat over conda.exe on Windows

---

NEWS.md
R/package.R
R/python.R

provide readline hook for Python input

---

NEWS.md
R/python.R
inst/python/rpytools/output.py
tests/testthat/test-python-output.R

better handle Python loggers in py_capture_output

---

src/python.cpp

hadn't seen this warning before or else this should have been part of the last Pandas-related PR :-)

avoid compiler warning

---

R/RcppExports.R
R/array.R
R/conversion.R
src/RcppExports.cpp
src/python.cpp

TODO: implement special cases for factors + POSIXt.

[WIP] improve R -> Pandas performance

---

R/use_python.R

See https://github.com/rstudio/reticulate/issues/649

Fix conda full path regex

---

NEWS.md
R/knitr-engine.R

Closes #645.
@cderv does this seem like the right fix to you?

work in output dir when creating plots

---

R/conda.R
R/pip.R
R/virtualenv.R
man/conda-tools.Rd
man/virtualenv-tools.Rd

Add optional pip_options argument

---

R/conversion.R

This pull request tries to solve the problem in the issue  #727.

sort indices of csr sparse matrix before convert to R dgRMatrix

---

DESCRIPTION
NEWS.md
R/utils-format.R
R/virtualenv.R
man/virtualenv-tools.Rd

updates for virtualenv_create

---

DESCRIPTION
NEWS.md
R/virtualenv.R
man/virtualenv-tools.Rd

virtualenv gains 'module', 'pip_version', 'setuptools_version'

---

R/conda.R
R/config.R

+ wrap `python_info()` in `tryCatch()`, since it errors on a non-env python
+ Allow `conda_run()` to succeed in a conda base environment

fix #1083: succeed binding to system and conda base python installation

---

R/conda.R
R/config.R
R/miniconda.R
R/package.R
R/utils.R
man/conda_python.Rd
reticulate.Rproj

Closes https://github.com/rstudio/reticulate/issues/1095.
cc: @t-kalinowski

prefer Anaconda to python versions found in hard-coded locations

---

vignettes/python_primer.Rmd

Closes https://github.com/rstudio/reticulate/issues/1135.

check for compatible version of python when building vignette

---

DESCRIPTION
NEWS.md

To merge if CRAN submission is accepted.

CRAN release 1.24

---

NEWS.md
R/conda.R
R/config.R

avoid `conda run`

---

R/use_python.R

PR for #1164 
Sorry, it is a bit awkward to squeeze the function's doc into an argument description.

1164-use-conda-doc-update

---

R/poetry.R

Thank you for the great package! 🤘🏻

Small typo

---

.Rbuildignore
CRAN-SUBMISSION
DESCRIPTION
NEWS.md
cran-comments.md

To be merged when CRAN accepts.
Close #1207

CRAN release 1.25

---

.github/workflows/R-CMD-check.yaml

+ make sure tests run with a python installation that has numpy

GHA updates

---

NEWS.md
R/knitr-engine.R
tests/testthat/resources/eng-reticulate-example.Rmd

Closes https://github.com/rstudio/reticulate/issues/583.

don't halt on parse error if error=TRUE

---

NEWS.md
src/python.cpp
tests/testthat/test-python-pandas.R

Fis `py_to_r()` for pandas dataframes with ordered categorical series

---

NEWS.md
R/conda.R
R/python-tools.R
R/use_python.R

address use of micromamba during initialization see #1378 and #1176

---

NEWS.md
R/pip.R
R/virtualenv.R
man/virtualenv-tools.Rd

accept `requirements` in `virtualenv_{install,create}`

---

vignettes/python_dependencies.Rmd

Spotted these while scanning through the vignette.

some small spelling fixes

---

R/array.R

Make sure we initialize python before calling `r_to_py_impl`

---

R/config.R
R/virtualenv.R

Improved error message if system python can't create a venv

---

R/config.R
R/zzz.R

Disable startup prompt from loading namespace in IDE.

---

R/config.R
R/python-tools.R

Closes #1149
Closes first task item in #1441

Better error message for broken venvs

---

NEWS.md
R/package.R
inst/python/rpytools/subprocess.py
tests/testthat/test-subprocess.R

patch `subprocess.Popen` on Windows/Rstudio

---

.github/workflows/R-CMD-check.yaml
R/miniconda.R
R/pyenv.R
R/utils.R

Expand `$USER` in `user_data_dir()` path.

---

R/virtualenv.R

Based on user suggestion in https://github.com/rstudio/tensorflow/issues/586#issuecomment-1863240061, we should use `RETICULATE_PYTHON` and similar when
searching for candidate Python virtualenv starters.

include `RETICULATE_PYTHON` in `virtualenv_starter()`

---

NEWS.md
R/knitr-engine.R

knitr: set matplotlib fig size in load hook

---

NEWS.md
R/config.R

don't discover python2 in `py_discover_config()`

---

.git-blame-ignore-revs
inst/config/config.py
inst/python/rpytools/generator.py
inst/python/rpytools/help.py
inst/python/rpytools/loader.py
inst/python/rpytools/output.py
inst/python/rpytools/signals.py
inst/python/rpytools/test.py
inst/python/rpytools/thread.py
tests/testthat/script.py

This PR applies Black to all the Python files. (Added now to minimize the diff size for an upcoming PR).

Format Python files with Black

---

src/python.cpp

`py_class_names()` is on the common path now for exporting `PyObject*`s to
R. If we're encountering an Exception in `py_class_names()`, then we blow up
the stack with infinite `py_fetch_error()` and `py_class_names()` calls without this patch.

Avoid calling `py_fetch_error()` from `py_class_names()`

---

NEWS.md
src/libpython.cpp
src/libpython.h
src/python.cpp
tests/testthat/test-python-numpy.R
tests/testthat/test-python-pandas.R

Adds compatibility with NumPy 2.0.
closes #1620

Add NumPy 2.0 Compatibility

---

NEWS.md
inst/config/config.py

Fix error when importing `config`

---

NEWS.md
src/reticulate_types.h
tests/testthat/test-delay-load.R

`[[` loads lazy modules

---

tools/compile-python.R

add `tools/compile-python.R` script

---

NEWS.md
R/virtualenv.R

Remove `+<tag>` suffix from Python version in `virtualenv_starter()`

---

R/virtualenv.R

Set `LD_LIBRARY_PATH` when probing candidate venv starters

---

inst/config/config.py

Fix module finder on Windows

---

R/py_require.R
man/py_require.Rd
vignettes/package.Rmd
vignettes/python_packages.Rmd

- Document return value in `?py_require()`

Refine `py_require()` docs

---

R/config.R
R/install.R
R/package.R
R/py_require.R
R/utils.R
tests/testthat/resources/import-test.R
tests/testthat/test-py_require.R

Use `tools::R_user_dir()` where possible, for CRAN compliance.

Change cache location per CRAN policy

---

NEWS.md
R/miniconda.R

`install_miniconda()`; stop if directory not empty

---

NEWS.md
R/install-python.R
R/pyenv.R
man/install_python.Rd

Fix `install_python()`

---

R/conversion.R

Fix POSIXt vectors with tz and length>1

---

R/py_require.R

Quick helper that might be useful in the future for quickly identifying which python package update broke a workflow.
```r
reticulate:::uv_diff_exclude_newer() # diff between today and 3 days ago
reticulate:::uv_diff_exclude_newer(-30) # diff between today and 30 days ago
```

Add experimental helper for diffing ephemeral venvs base on date.

---

NEWS.md
R/zzz.R

Pairs with https://github.com/posit-dev/positron/pull/8769

Enable reticulate integration when running within Positron

---

NEWS.md
R/py_require.R
R/zzz.R
man/py_require.Rd
tests/testthat/helper-py-require.R

Auto clear `uv` cache

---

DESCRIPTION
NEWS.md
R/repl.R
man/as.character.python.builtin.bytes.Rd
man/as.character.python.builtin.str.Rd
tests/testthat/test-repl-magics.R

Fix expansion of `!!` in a string literal
